import { FastifyInstance } from 'fastify';
import { Message } from '../../ai/providers.js';
import { isAutoSaveModel } from '../../../services/CodeAutoSaveService.js';
import { enhanceWithWebSearch } from '../../../services/WebSearchService.js';
import { MemoryService } from '../../memory/service.js';
import { ToolContext } from '../types.js';
import { detectDocumentFormat } from '../streaming.js';
import { injectGuardrailPolicy } from './rag-context.js';

/**
 * Inject system prompts for coding models, web search, tools, doc generation, and memory.
 */
export async function injectSystemPrompts(
  fastify: FastifyInstance,
  messages: Message[],
  opts: {
    model: string;
    userMessage: string;
    userId: number;
    supportsTools: boolean;
    toolContext: ToolContext | null;
    attachmentIds?: number[];
    forceWebSearch?: boolean;
  }
): Promise<{ webSearchPerformed: boolean; autoGenerateDoc: false | 'docx' | 'pptx' | 'xlsx' | 'pdf'; webSearchResults?: { title: string; url: string; snippet: string; source?: string }[] }> {
  // Add coding system prompt for coder models
  if (isAutoSaveModel(opts.model)) {
    const codingSystemPrompt = `Sei un esperto assistente di programmazione. Quando generi codice:
1. Scrivi codice completo e pronto per la produzione
2. Includi tutti gli import e le dipendenze necessarie
3. Aggiungi commenti chiari in italiano che spiegano ogni sezione
4. Usa il formato commento per il nome file: # filename.py o // filename.js
5. Genera applicazioni complete, non solo frammenti
6. Includi gestione errori e validazione input
7. Segui le best practice del linguaggio

Il codice che generi verr\u00e0 salvato automaticamente nella cartella condivisa. Usa commenti chiari per i nomi dei file.`;

    const systemIndex = messages.findIndex(m => m.role === 'system');
    if (systemIndex >= 0) {
      messages[systemIndex].content = codingSystemPrompt + '\n\n' + messages[systemIndex].content;
    } else {
      messages.unshift({ role: 'system', content: codingSystemPrompt });
    }
  }

  // Check if web search is needed (keyword-based auto-detect OR forced by user toggle)
  let webSearchPerformed = false;
  let webSearchResults: { title: string; url: string; snippet: string; source?: string }[] | undefined;
  try {
    const searchResult = await enhanceWithWebSearch(opts.userMessage, opts.forceWebSearch);
    if (searchResult.shouldSearch && searchResult.searchContext) {
      webSearchPerformed = true;
      webSearchResults = searchResult.searchResponse?.results;
      fastify.log.info(`[Chat] Web search performed, found ${searchResult.searchResponse?.results?.length || 0} results`);
      const searchSystemMessage = `Hai accesso ai risultati di ricerca web aggiornati. Usali per fornire informazioni accurate e attuali.\n${searchResult.searchContext}`;
      const systemIndex = messages.findIndex(m => m.role === 'system');
      if (systemIndex >= 0) {
        messages[systemIndex].content += '\n\n' + searchSystemMessage;
      } else {
        messages.unshift({ role: 'system', content: searchSystemMessage });
      }
    }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  } catch (searchError: any) {
    fastify.log.warn(`[Chat] Web search failed: ${searchError.message}`);
  }

  // Inject Tool System Prompt
  if (opts.toolContext) {
    const toolSystemPrompt = `\n\n[STRUMENTI DISPONIBILI]
Hai accesso a questi strumenti:
1. **execute_python(code)**: Esegui Python in una sandbox. In Python, usa l'oggetto "tool" pre-inizializzato:
   - tool.read_file(path), tool.write_file(path, content), tool.list_files(path)
   - tool.web_search(query), tool.http_get(url), tool.web_extract(url)
   - tool.vector_search(query), tool.vector_upsert(text, metadata)
   - tool.dataframe(data) per DataFrame pandas. Usa print() per l'output.
2. **vector_memory_search(query)**: Cerca nella memoria vettoriale contesto rilevante.
3. **generate_word_document / generate_excel_document / generate_powerpoint_document**: Crea file Office.
4. **get_attachment_text(attachment_id)**: Leggi il testo COMPLETO di un file caricato.
5. **web_search(query)**: Cerca informazioni aggiornate sul web.

[ISTRUZIONI CRITICHE]
- Il contenuto di qualsiasi file caricato (PDF, DOCX, ecc.) \u00e8 GI\u00c0 INCLUSO nel messaggio utente sopra, tra i marcatori [Allegato ...] e [Fine allegato].
- PUOI leggerlo. NON dire che non puoi leggere o vedere il file. Il testo \u00c8 il contenuto del file.
- Per compiti complessi multi-step, preferisci execute_python per orchestrare tutto in una sola chiamata.
- USA SEMPRE gli strumenti per le operazioni sui file. NON dire MAI che non puoi creare file.
- Usa percorsi relativi come "output/translated.docx".`;

    const systemIndex = messages.findIndex(m => m.role === 'system');
    if (systemIndex >= 0) {
      messages[systemIndex].content += toolSystemPrompt;
    } else {
      messages.unshift({ role: 'system', content: toolSystemPrompt });
    }
  }

  // Inject guardrail policy (shared function used by all chat modes for AI ACT compliance)
  await injectGuardrailPolicy(fastify, messages, opts.userId);

  // Detect document generation requests
  const autoGenerateDoc = detectDocumentFormat(opts.userMessage, opts.attachmentIds);
  fastify.log.info(`[Chat] DocGen detection: format=${autoGenerateDoc}, supportsTools=${opts.supportsTools}`);

  if (autoGenerateDoc) {
    const formatName = autoGenerateDoc === 'pptx' ? 'presentazione PowerPoint' :
      autoGenerateDoc === 'xlsx' ? 'foglio Excel' :
        autoGenerateDoc === 'pdf' ? 'PDF' : 'documento Word';

    let docGenSystemPrompt: string;
    if (opts.supportsTools) {
      const toolHint = autoGenerateDoc === 'pptx'
        ? `Hai a disposizione il tool "generate_powerpoint_document". DEVI usarlo per generare la presentazione.
Crea slide ben strutturate con titoli chiari e contenuto organizzato in punti.
Se il messaggio contiene un allegato, il suo contenuto testuale \u00e8 GI\u00c0 INCLUSO nel messaggio tra i marcatori [Allegato ...] e [Fine allegato].
NON dire che non puoi leggere il file. Il testo \u00c8 il contenuto del file.
Se per qualche motivo non riesci a usare il tool, scrivi il contenuto strutturato con titoli ## o ### per separare le slide \u2014 il sistema generer\u00e0 automaticamente il file.`
        : autoGenerateDoc === 'xlsx'
          ? `Hai a disposizione il tool "generate_excel_document". DEVI usarlo per generare il foglio Excel.
Se il messaggio contiene un allegato, il suo contenuto testuale \u00e8 GI\u00c0 INCLUSO nel messaggio.
Se non riesci a usare il tool, scrivi i dati in formato tabellare nella risposta.`
          : autoGenerateDoc === 'docx'
            ? `Hai a disposizione il tool "generate_word_document". DEVI usarlo per generare il documento Word.
Se il messaggio contiene un allegato, il suo contenuto testuale \u00e8 GI\u00c0 INCLUSO nel messaggio tra i marcatori [Allegato ...] e [Fine allegato].
NON dire che non puoi leggere il file. Il testo \u00c8 il contenuto del file.

REGOLA CRITICA: Usa SEMPRE il tool generate_word_document passando il contenuto come parametro "content".
- NON scrivere il contenuto intero nella chat \u2014 usa DIRETTAMENTE il tool.
- Per conversioni pure, passa il contenuto dell'allegato cos\u00ec com'\u00e8 al tool.
- Per elaborazioni (traduzione, modifica, ecc.), elabora il contenuto e poi passa il risultato al tool.
Se per qualche motivo non riesci a usare il tool, scrivi il contenuto nella risposta come fallback.`
            : `Se il messaggio contiene un allegato, il suo contenuto testuale \u00e8 GI\u00c0 INCLUSO nel messaggio tra i marcatori [Allegato ...] e [Fine allegato].
NON dire che non puoi leggere il file. Il testo \u00c8 il contenuto del file.

REGOLA CRITICA PER CONVERSIONE IN PDF:
- Se l'utente chiede di convertire, RIPRODUCE il contenuto INTERO dell'allegato, senza riassumerlo.
- NON aggiungere introduzioni come "Ecco il contenuto..." \u2014 scrivi DIRETTAMENTE il contenuto.
- Se chiede di elaborare, tradurre o modificare, elabora come richiesto.
Il sistema generer\u00e0 automaticamente il ${formatName} dalla tua risposta.`;
      docGenSystemPrompt = `\n\n[ISTRUZIONI GENERAZIONE DOCUMENTO]\n${toolHint}`;
    } else {
      const pptxExtra = autoGenerateDoc === 'pptx' ? `
6. Struttura il contenuto con titoli (## o ###) per separare le slide
7. Ogni sezione diventer\u00e0 una slide nella presentazione
8. Per ogni slide, scrivi un titolo chiaro e poi il contenuto con punti elenco` : '';
      docGenSystemPrompt = `\n\n[ISTRUZIONI IMPORTANTI]
Il contenuto di qualsiasi file caricato (PDF, DOCX, ecc.) \u00e8 GI\u00c0 INCLUSO nel messaggio utente sopra, tra i marcatori [Allegato ...] e [Fine allegato].
Tu PUOI leggerlo. NON dire che non puoi leggere o vedere il file. Il testo \u00c8 il contenuto del file.

Quando l'utente chiede di tradurre, creare o elaborare un documento:
1. Elabora la richiesta completamente (traduci, modifica, formatta, ecc.)
2. Scrivi il contenuto COMPLETO del documento tradotto/elaborato nella tua risposta
3. NON suggerire codice Python o librerie esterne
4. NON dire che non puoi creare file \u2014 il sistema generer\u00e0 automaticamente il ${formatName} dalla tua risposta
5. Concentrati SOLO sul contenuto: traduci/elabora tutto il testo e scrivilo nella risposta${pptxExtra}

REGOLA CRITICA PER CONVERSIONE FORMATO:
Se l'utente chiede di CONVERTIRE un file in un altro formato (es. "converti il PDF in DOCX/Word"):
- RIPRODUCE il contenuto INTERO e INTEGRALE dell'allegato, senza riassumerlo o ometterne parti
- NON aggiungere introduzioni, spiegazioni o commenti \u2014 scrivi DIRETTAMENTE il contenuto del file
- Mantieni la struttura originale: paragrafi, titoli, elenchi, tabelle`;
    }

    const systemIndex = messages.findIndex(m => m.role === 'system');
    if (systemIndex >= 0) {
      messages[systemIndex].content += docGenSystemPrompt;
    } else {
      messages.unshift({ role: 'system', content: docGenSystemPrompt });
    }
  }

  // Inject memory context for new conversations
  try {
    const memoryService = new MemoryService(fastify.db);
    const msgCount = messages.filter(m => m.role === 'user').length;
    if (msgCount <= 1) {
      const memoryContext = await memoryService.getContextForNewChat(opts.userId);
      if (memoryContext) {
        const systemIndex = messages.findIndex(m => m.role === 'system');
        if (systemIndex >= 0) {
          messages[systemIndex].content += '\n\n[Memory Context]\n' + memoryContext;
        } else {
          messages.unshift({ role: 'system', content: '[Memory Context]\n' + memoryContext });
        }
        fastify.log.info(`[Memory] Injected context for user ${opts.userId}`);
      }
    }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  } catch (memErr: any) {
    fastify.log.warn(`[Memory] Context injection failed: ${memErr.message}`);
  }

  // Inject user skills system prompts
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
    const [skillRows] = await fastify.db.execute<any[]>(
      `SELECT s.name, s.display_name, s.system_prompt, s.category, us.custom_prompt_addition
       FROM user_skills us
       JOIN skills s ON s.id = us.skill_id
       WHERE us.user_id = ? AND us.is_enabled = TRUE AND s.is_active = TRUE AND s.system_prompt IS NOT NULL AND s.system_prompt != ''`,
      [opts.userId]
    );
    if (skillRows.length > 0) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
      const skillPrompts = skillRows.map((sk: any) => {
        let prompt = `[Skill: ${sk.display_name || sk.name}]\n${sk.system_prompt}`;
        if (sk.custom_prompt_addition) {
          prompt += `\n${sk.custom_prompt_addition}`;
        }
        return prompt;
      });
      const skillSystemPrompt = `\n\n[COMPETENZE ATTIVE]\n${skillPrompts.join('\n\n')}`;
      const systemIndex = messages.findIndex(m => m.role === 'system');
      if (systemIndex >= 0) {
        messages[systemIndex].content += skillSystemPrompt;
      } else {
        messages.unshift({ role: 'system', content: skillSystemPrompt });
      }
      fastify.log.info(`[Skills] Injected ${skillRows.length} skill prompt(s) for user ${opts.userId}`);
    }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  } catch (skillErr: any) {
    fastify.log.warn(`[Skills] Skill injection failed: ${skillErr.message}`);
  }

  return { webSearchPerformed, autoGenerateDoc, webSearchResults };
}

/**
 * Ensure a base system prompt exists with Italian language instruction.
 */
export function ensureItalianSystemPrompt(messages: Message[]): void {
  const systemIndex = messages.findIndex(m => m.role === 'system');
  const italianLanguageInstruction = 'IMPORTANT: Rispondi SEMPRE in italiano, indipendentemente dalla lingua del system prompt. Usa un tono preciso, amichevole e professionale.';
  if (systemIndex >= 0) {
    if (!messages[systemIndex].content.includes('Rispondi SEMPRE in italiano')) {
      messages[systemIndex] = {
        ...messages[systemIndex],
        content: messages[systemIndex].content + '\n\n' + italianLanguageInstruction,
      };
    }
  } else {
    const currentDate = new Date().toLocaleDateString('it-IT', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    messages.unshift({ role: 'system', content: `Sei un assistente AI utile e competente. Oggi \u00e8 ${currentDate}.\n${italianLanguageInstruction}` });
  }
}
