/**
 * CompletionExtrasBuilder.test.ts — DEBT-87-L
 *
 * Unit tests for buildCompletionExtras and applyForceShortOutputMessages.
 * Coverage target: ≥80%
 *
 * Tests:
 *  1. opus-4.5 adaptive thinking
 *  2. opus-4.6 adaptive thinking
 *  3. budgetTokens for non-adaptive opus
 *  4. tierTokenCap vs baseMaxTokens (min wins)
 *  5. applyForceShortOutput=true → capped at 512
 *  6. applyForceShortOutputMessages prepend
 *  7. applyForceShortOutputMessages idempotent (no double prepend)
 *  8. autoGenerateDoc toolChoice=any
 *  9. cacheControl set for anthropic
 * 10. ollama thinking = true
 */

import { describe, it, expect } from 'vitest';
import {
  buildCompletionExtras,
  applyForceShortOutputMessages,
  type CompletionExtrasBuilderOptions,
} from './CompletionExtrasBuilder.js';
import type { Message } from '../../ai/providers.js';

// ── Helpers ───────────────────────────────────────────────────────────────────

function baseOpts(overrides: Partial<CompletionExtrasBuilderOptions> = {}): CompletionExtrasBuilderOptions {
  return {
    model: 'claude-3-sonnet',
    providerName: 'anthropic',
    modelConfig: {
      supportsThinking: false,
      supportsCaching: false,
      maxOutputTokens: 4096,
      temperature: 0.7,
    },
    nativeDocBlocks: [],
    autoGenerateDoc: false,
    toolDefs: undefined,
    applyForceShortOutput: false,
    routingDecision: null,
    ...overrides,
  };
}

function userMsg(content: string): Message {
  return { role: 'user', content };
}

function systemMsg(content: string): Message {
  return { role: 'system', content };
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe('buildCompletionExtras — thinking', () => {
  it('opus-4-5: uses adaptive thinking type', () => {
    const { completionExtras } = buildCompletionExtras(baseOpts({
      model: 'claude-opus-4-5',
      modelConfig: { supportsThinking: true, maxOutputTokens: 8192 },
    }));
    expect(completionExtras.thinking?.type).toBe('adaptive');
  });

  it('opus-4-6: uses adaptive thinking type', () => {
    const { completionExtras } = buildCompletionExtras(baseOpts({
      model: 'claude-opus-4-6',
      modelConfig: { supportsThinking: true, maxOutputTokens: 8192 },
    }));
    expect(completionExtras.thinking?.type).toBe('adaptive');
  });

  it('opus (non-adaptive): uses enabled thinking with budgetTokens', () => {
    const { completionExtras } = buildCompletionExtras(baseOpts({
      model: 'claude-opus-3',
      modelConfig: { supportsThinking: true, maxOutputTokens: 8192 },
    }));
    expect(completionExtras.thinking?.type).toBe('enabled');
    expect(completionExtras.thinking?.budgetTokens).toBeGreaterThanOrEqual(1024);
    expect(completionExtras.thinking?.budgetTokens).toBeLessThanOrEqual(16000);
  });

  it('non-opus with supportsThinking: uses enabled with budgetTokens', () => {
    const { completionExtras } = buildCompletionExtras(baseOpts({
      model: 'claude-sonnet-thinking',
      modelConfig: { supportsThinking: true, maxOutputTokens: 4096 },
    }));
    expect(completionExtras.thinking).toBeDefined();
    expect(completionExtras.thinking?.budgetTokens).toBeGreaterThanOrEqual(1024);
  });

  it('ollama with supportsThinking: thinking = true', () => {
    const { completionExtras } = buildCompletionExtras(baseOpts({
      model: 'qwen3',
      providerName: 'ollama',
      modelConfig: { supportsThinking: true },
    }));
    expect(completionExtras.thinking).toBe(true);
  });

  it('no thinking when supportsThinking=false', () => {
    const { completionExtras } = buildCompletionExtras(baseOpts({
      modelConfig: { supportsThinking: false },
    }));
    expect(completionExtras.thinking).toBeUndefined();
  });
});

describe('buildCompletionExtras — token caps', () => {
  it('tierTokenCap < baseMaxTokens: uses tierTokenCap', () => {
    const { effectiveMaxTokens } = buildCompletionExtras(baseOpts({
      modelConfig: { maxOutputTokens: 8192 },
      routingDecision: { tier: 'FAST', maxOutputTokens: 2048 } as never,
    }));
    expect(effectiveMaxTokens).toBe(2048);
  });

  it('tierTokenCap > baseMaxTokens: uses baseMaxTokens', () => {
    const { effectiveMaxTokens } = buildCompletionExtras(baseOpts({
      modelConfig: { maxOutputTokens: 2048 },
      routingDecision: { tier: 'POWERFUL', maxOutputTokens: 16000 } as never,
    }));
    expect(effectiveMaxTokens).toBe(2048);
  });

  it('no routingDecision: uses baseMaxTokens', () => {
    const { effectiveMaxTokens } = buildCompletionExtras(baseOpts({
      modelConfig: { maxOutputTokens: 4096 },
    }));
    expect(effectiveMaxTokens).toBe(4096);
  });

  it('applyForceShortOutput=true: caps at 512', () => {
    const { effectiveMaxTokens, effectiveTemperature } = buildCompletionExtras(baseOpts({
      applyForceShortOutput: true,
      modelConfig: { maxOutputTokens: 8192, temperature: 0.7 },
    }));
    expect(effectiveMaxTokens).toBe(512);
    expect(effectiveTemperature).toBe(0);
  });

  it('applyForceShortOutput=false: temperature from modelConfig', () => {
    const { effectiveTemperature } = buildCompletionExtras(baseOpts({
      applyForceShortOutput: false,
      modelConfig: { temperature: 0.5 },
    }));
    expect(effectiveTemperature).toBe(0.5);
  });
});

describe('buildCompletionExtras — toolChoice', () => {
  it('autoGenerateDoc=docx with tools: sets toolChoice=any', () => {
    const { completionExtras } = buildCompletionExtras(baseOpts({
      autoGenerateDoc: 'docx',
      toolDefs: [{ name: 'generate_word_document' }],
    }));
    expect(completionExtras.toolChoice).toBe('any');
  });

  it('autoGenerateDoc=false: no toolChoice', () => {
    const { completionExtras } = buildCompletionExtras(baseOpts({
      autoGenerateDoc: false,
      toolDefs: [{ name: 'some_tool' }],
    }));
    expect(completionExtras.toolChoice).toBeUndefined();
  });
});

describe('buildCompletionExtras — anthropic extras', () => {
  it('cacheControl set from modelConfig.supportsCaching', () => {
    const { completionExtras } = buildCompletionExtras(baseOpts({
      modelConfig: { supportsCaching: true },
    }));
    expect(completionExtras.cacheControl).toBe(true);
  });

  it('nativeDocBlocks passed to documentBlocks for anthropic', () => {
    const block = { type: 'document', source: { type: 'base64', media_type: 'application/pdf', data: 'abc' } };
    const { completionExtras } = buildCompletionExtras(baseOpts({
      nativeDocBlocks: [block],
    }));
    expect(completionExtras.documentBlocks).toHaveLength(1);
  });
});

describe('applyForceShortOutputMessages', () => {
  it('prepends concise instruction when no system message present', () => {
    const msgs: Message[] = [userMsg('Hello')];
    const result = applyForceShortOutputMessages(msgs);
    expect(result[0].role).toBe('system');
    expect(result[0].content).toContain('concise assistant');
    expect(result).toHaveLength(2);
  });

  it('idempotent: does not double-prepend if concise instruction already present', () => {
    const msgs: Message[] = [systemMsg('You are a concise assistant. Answer in maximum 3 sentences unless the user explicitly asks for more.'), userMsg('Hi')];
    const result = applyForceShortOutputMessages(msgs);
    expect(result).toHaveLength(2);
    // Still only one system message
    expect(result.filter(m => m.role === 'system')).toHaveLength(1);
  });

  it('does not mutate the original messages array', () => {
    const msgs: Message[] = [userMsg('Test')];
    const result = applyForceShortOutputMessages(msgs);
    expect(msgs).toHaveLength(1); // original unchanged
    expect(result).toHaveLength(2);
  });
});
