/**
 * CompletionExtrasBuilder — DEBT-84-A / T5
 *
 * Extracted from completions.ts.
 * Builds the completionExtras object for provider.streamComplete():
 * - Thinking budget (Anthropic / Ollama)
 * - Cache control (Anthropic)
 * - Native document blocks (Anthropic)
 * - Tool choice override for doc generation (B1)
 * - Effective token / temperature caps (PERF-79-B3, DEBT-81-G)
 * - Concise output system message prepend (force_short_output)
 */

import type { Message } from '../../ai/providers.js';
import type { RoutingDecision } from '../../../services/ModelRouter.js';

interface ModelConfig {
  supportsThinking?: boolean;
  supportsCaching?: boolean;
  maxOutputTokens?: number;
  temperature?: number;
}

export interface CompletionExtrasBuilderOptions {
  readonly model: string;
  readonly providerName: string;
  readonly modelConfig: ModelConfig;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  readonly nativeDocBlocks: any[];
  readonly autoGenerateDoc: false | string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- tool defs type varies per provider
  readonly toolDefs: any[] | undefined;
  readonly applyForceShortOutput: boolean;
  readonly routingDecision: RoutingDecision | null;
}

export interface CompletionExtrasBuilderResult {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  readonly completionExtras: Record<string, any>;
  readonly effectiveMaxTokens: number;
  readonly effectiveTemperature: number;
}

/**
 * Build completionExtras and effective token/temperature settings.
 * Pure function — no side effects, returns new objects only.
 */
export function buildCompletionExtras(
  opts: CompletionExtrasBuilderOptions,
): CompletionExtrasBuilderResult {
  const { model, providerName, modelConfig, nativeDocBlocks, autoGenerateDoc,
    toolDefs, applyForceShortOutput, routingDecision } = opts;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  const completionExtras: Record<string, any> = {};
  const isAnthropic = providerName === 'anthropic';

  if (modelConfig.supportsThinking) {
    if (isAnthropic) {
      const isOpus = model.includes('opus');
      const maxOut = modelConfig.maxOutputTokens || 4096;
      const supportsAdaptive = isOpus && (model.includes('opus-4-5') || model.includes('opus-4-6'));
      if (supportsAdaptive) {
        completionExtras.thinking = { type: 'adaptive' as const };
      } else if (isOpus) {
        const budgetTokens = Math.min(16000, maxOut - 1024);
        if (budgetTokens >= 1024) completionExtras.thinking = { type: 'enabled' as const, budgetTokens };
      } else {
        const budgetTokens = Math.min(16000, maxOut - 1024);
        if (budgetTokens >= 1024) completionExtras.thinking = { type: 'enabled' as const, budgetTokens };
      }
    } else if (providerName === 'ollama') {
      completionExtras.thinking = true;
    }
    // vLLM handles thinking natively via reasoning_content — no workarounds needed
  }

  if (isAnthropic) {
    completionExtras.cacheControl = modelConfig.supportsCaching;
    if (nativeDocBlocks.length > 0) completionExtras.documentBlocks = nativeDocBlocks;
  }

  // B1: Force tool usage when document generation is expected
  if (autoGenerateDoc && typeof autoGenerateDoc === 'string'
    && /^(docx|xlsx|pptx)$/i.test(autoGenerateDoc) && toolDefs && toolDefs.length > 0) {
    completionExtras.toolChoice = 'any';
  }

  // PERF-79-B3 / DEBT-81-G: effective token cap and temperature
  const tierTokenCap = routingDecision?.maxOutputTokens ?? null;
  const baseMaxTokens = modelConfig.maxOutputTokens ?? 4096;
  const effectiveMaxTokens = applyForceShortOutput
    ? Math.min(baseMaxTokens, 512)
    : tierTokenCap !== null
      ? Math.min(baseMaxTokens, tierTokenCap)
      : baseMaxTokens;
  const effectiveTemperature = applyForceShortOutput ? 0 : (modelConfig.temperature ?? 0.7);

  return { completionExtras, effectiveMaxTokens, effectiveTemperature };
}

/**
 * Prepend concise-output instruction when force_short_output is active.
 * Returns a new messages array (immutable update).
 */
export function applyForceShortOutputMessages(messages: Message[]): Message[] {
  const conciseInstruction: Message = {
    role: 'system',
    content: 'You are a concise assistant. Answer in maximum 3 sentences unless the user explicitly asks for more.',
  };
  if (messages.some(m => m.role === 'system' && m.content?.toString().includes('concise assistant'))) {
    return messages;
  }
  return [conciseInstruction, ...messages];
}
