/**
 * PostProcessingRunner — Document auto-generation and code auto-save.
 *
 * HIGH-1: Extracted from completions.ts to keep that file under 800 lines.
 *
 * Handles the two post-stream processing steps:
 *  1. Document auto-generation (docx / xlsx / pptx / pdf) from the LLM response.
 *  2. Code block auto-save for agent-class models.
 *
 * Returns the updated fullResponse (may have a download notification appended).
 */

import type { FastifyBaseLogger, FastifyReply } from 'fastify';
import { autoGenerateDocument } from '../streaming.js';
import { saveCodeBlocks, formatSavedFilesNotification, isAutoSaveModel } from '../../../services/CodeAutoSaveService.js';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface PostProcessingOptions {
  readonly fullResponse: string;
  readonly autoGenerateDoc: false | 'docx' | 'pptx' | 'xlsx' | 'pdf';
  readonly originalMessage: string;
  readonly model: string;
  readonly conversationId: number;
  readonly reply: FastifyReply;
  readonly log: FastifyBaseLogger;
}

export interface PostProcessingResult {
  readonly fullResponse: string;
}

// ─── Runner ──────────────────────────────────────────────────────────────────

/**
 * Runs post-processing on the LLM response:
 *  1. Optionally generates a document from the text and appends a download link.
 *  2. Optionally auto-saves code blocks for agent-class models.
 */
export async function runPostProcessing(
  opts: PostProcessingOptions,
): Promise<PostProcessingResult> {
  const { autoGenerateDoc, originalMessage, model, conversationId, reply, log } = opts;
  let { fullResponse } = opts;

  // Step 1: auto-generate document
  if (autoGenerateDoc) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any -- format string union must be cast for legacy streaming.ts signature
      const docNotification = await autoGenerateDocument(reply, fullResponse, autoGenerateDoc as any, originalMessage, log);
      fullResponse += docNotification;
    } catch (docErr: unknown) {
      const msg = docErr instanceof Error ? docErr.message : String(docErr);
      log.error(`[PostProcessingRunner] Auto document generation failed: ${msg}`);
      const errorNotice = `\n\nGenerazione documento fallita. Riprova o usa un formato diverso.`;
      reply.raw.write(`data: ${JSON.stringify({ content: errorNotice, done: false })}\n\n`);
      fullResponse += errorNotice;
    }
  }

  // Step 2: auto-save code blocks
  if (isAutoSaveModel(model) && fullResponse.length > 50) {
    try {
      const saveResult = await saveCodeBlocks(fullResponse, { projectName: `session_${conversationId}` });
      if (saveResult.savedFiles.length > 0) {
        const notification = formatSavedFilesNotification(saveResult);
        reply.raw.write(`data: ${JSON.stringify({
          content: notification,
          done: false,
          autoSave: true,
          savedFiles: saveResult.savedFiles.map(f => ({
            filename: f.filename,
            language: f.language,
            path: f.path.replace('/data/shared-projects', '\\\\192.168.1.123\\projects').replace(/\//g, '\\\\'),
          })),
        })}\n\n`);
        log.info(`[PostProcessingRunner] Auto-saved ${saveResult.savedFiles.length} code files for model ${model}`);
      }
    } catch (saveError: unknown) {
      log.warn(`[PostProcessingRunner] Auto-save failed: ${saveError instanceof Error ? saveError.message : 'Unknown error'}`);
    }
  }

  return { fullResponse };
}
