/**
 * PromptInjectionRunner — DEBT-84-C
 *
 * Extracted from SafetyContentRunner.ts as part of the T4 refactor.
 *
 * Handles chat mode detection and system prompt injection:
 * - Brainstorm mode: injects brainstorm system prompt + optional doc-gen prompt
 * - RAG mode: injects RAG system prompt, recalls vector memories
 * - Free mode: injects agent chain system prompts, optional web search
 *
 * Returns updated messages, recalledVectorMemories, webSearchPerformed, autoGenerateDoc.
 * May short-circuit (abort=true) if AgentChain fast_reply fires.
 */

import type { FastifyInstance, FastifyReply } from 'fastify';
import type { Message } from '../../ai/providers.js';
import { SafetyResult, ToolContext } from '../types.js';
import {
  injectBrainstormSystemPrompt, injectRAGSystemPrompt, injectSystemPrompts,
  ensureItalianSystemPrompt,
} from '../context-builder.js';
import { detectDocumentFormat, sendFastReply } from '../streaming.js';

export interface PromptInjectionOptions {
  readonly model: string;
  readonly userMessage: string;
  readonly userId: number;
  readonly conversationId: number;
  readonly chatMode?: 'free' | 'rag' | 'brainstorm';
  readonly useRag?: boolean;
  readonly documentIds?: number[];
  readonly attachmentIds?: number[];
  readonly forceWebSearch?: boolean;
  readonly supportsTools: boolean;
  readonly toolContext: ToolContext | null;
  readonly providerName: string;
  readonly safetyResult: SafetyResult;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  readonly conversation: any;
  readonly hookCtx: Readonly<{ userId: number; conversationId: number }>;
  readonly reply: FastifyReply;
}

export interface PromptInjectionResult {
  /** True when AgentChain fired fast_reply (response already sent). */
  readonly abort: boolean;
  readonly messages: Message[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  readonly recalledVectorMemories: { episodic: any[]; declarative: any[]; procedural: any[] } | null;
  readonly webSearchPerformed: boolean;
  readonly autoGenerateDoc: false | 'docx' | 'pptx' | 'xlsx' | 'pdf';
}

/**
 * Run brainstorm / RAG / free-mode system prompt injection.
 * May short-circuit with abort=true if AgentChain triggers a fast_reply.
 */
export async function runPromptInjection(
  fastify: FastifyInstance,
  opts: PromptInjectionOptions,
  messagesIn: Message[],
): Promise<PromptInjectionResult> {
  const { model, userMessage, userId, conversationId, chatMode, useRag, documentIds,
    attachmentIds, forceWebSearch, supportsTools, toolContext, providerName,
    safetyResult, conversation, hookCtx, reply } = opts;

  let messages = [...messagesIn];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  let recalledVectorMemories: { episodic: any[]; declarative: any[]; procedural: any[] } | null = null;
  let webSearchPerformed = false;
  let autoGenerateDoc: false | 'docx' | 'pptx' | 'xlsx' | 'pdf' = false;

  const effectiveChatMode = chatMode
    || (useRag ? 'rag' : undefined)
    || conversation?.chat_mode
    || 'free';

  if (effectiveChatMode === 'brainstorm') {
    fastify.log.info(`[Chat] Brainstorm mode active for user ${userId}`);
    await injectBrainstormSystemPrompt(fastify, messages, userId);

    autoGenerateDoc = detectDocumentFormat(userMessage, attachmentIds);
    if (autoGenerateDoc) {
      fastify.log.info(`[Chat] Brainstorm + DocGen detected: format=${autoGenerateDoc}`);
      const formatName = autoGenerateDoc === 'pptx' ? 'presentazione PowerPoint' :
        autoGenerateDoc === 'xlsx' ? 'foglio Excel' :
          autoGenerateDoc === 'pdf' ? 'PDF' : 'documento Word';
      const toolName = autoGenerateDoc === 'pptx' ? 'generate_powerpoint_document' :
        autoGenerateDoc === 'xlsx' ? 'generate_excel_document' :
          autoGenerateDoc === 'docx' ? 'generate_word_document' : null;

      let docGenPrompt: string;
      if (toolName && supportsTools) {
        docGenPrompt = `\n\n[ISTRUZIONI GENERAZIONE DOCUMENTO]\nHai a disposizione il tool "${toolName}". DEVI usarlo per generare il ${formatName}.\nREGOLA CRITICA: Usa SEMPRE il tool passando il contenuto come parametro "content".\n- NON scrivere il contenuto intero nella chat — usa DIRETTAMENTE il tool.\nSe per qualche motivo non riesci a usare il tool, scrivi il contenuto nella risposta come fallback.`;
      } else {
        docGenPrompt = `\n\n[ISTRUZIONI GENERAZIONE DOCUMENTO]\nL'utente vuole un ${formatName}. Scrivi il contenuto COMPLETO nella risposta.\nIl sistema genererà automaticamente il ${formatName} dalla tua risposta.\nNON suggerire codice o librerie esterne — scrivi DIRETTAMENTE il contenuto.`;
      }

      const systemIndex = messages.findIndex(m => m.role === 'system');
      if (systemIndex >= 0) {
        // Immutable update per coding-style.md
        messages = messages.map((m, i) =>
          i === systemIndex ? { ...m, content: (m.content as string) + docGenPrompt } : m
        );
      } else {
        messages = [{ role: 'system', content: docGenPrompt }, ...messages];
      }
    }
  } else if (effectiveChatMode === 'rag') {
    fastify.log.info(`[Chat] RAG mode active for user ${userId}`);
    const ragResult = await injectRAGSystemPrompt(fastify, messages, {
      userMessage,
      userId,
      documentIds,
    });

    const ragChunks = ragResult.chunks;
    const ragWebResults = ragResult.webResults;

    recalledVectorMemories = {
      episodic: [],
      declarative: [
        ...ragChunks.map((r: { id: unknown; content: string; score?: number; metadata?: Record<string, unknown> }) => ({
          id: r.id,
          content: r.content,
          score: r.score,
          metadata: { ...(r.metadata || {}), type: 'document' },
        })),
        ...ragWebResults.map((r, idx) => ({
          id: `web_${idx}`,
          content: r.snippet || r.title,
          score: 1 - (idx * 0.05),
          metadata: {
            originalName: r.source || (() => { try { return new URL(r.url).hostname; } catch { return r.url || 'web'; } })(),
            url: r.url,
            title: r.title,
            type: 'web_search',
          },
        })),
      ],
      procedural: [],
    };
  } else {
    const injectResults = await injectSystemPrompts(fastify, messages, {
      model, userMessage, userId,
      supportsTools, toolContext, attachmentIds,
      forceWebSearch,
    });
    webSearchPerformed = injectResults.webSearchPerformed;
    autoGenerateDoc = injectResults.autoGenerateDoc;

    if (webSearchPerformed && injectResults.webSearchResults?.length) {
      fastify.log.info(`[Chat] Using ${injectResults.webSearchResults.length} web search results as sources instead of vector memories`);
      recalledVectorMemories = {
        episodic: [],
        declarative: injectResults.webSearchResults.map((r, idx) => ({
          id: idx + 1,
          content: r.snippet || r.title,
          score: 1 - (idx * 0.05),
          metadata: {
            originalName: r.source || (() => { try { return new URL(r.url).hostname; } catch { return r.url || 'web'; } })(),
            url: r.url, title: r.title, type: 'web_search',
          },
        })),
        procedural: [],
      };
    }

    // Agent Chain: memory recall + prompt templates
    try {
      const { AgentChainService } = await import('../../../services/AgentChainService.js');
      const agentChain = new AgentChainService(fastify, fastify.db);
      const chainResult = await agentChain.execute({
        userId, conversationId, userMessage, messages, model, hookCtx,
      });
      if (chainResult.skippedByFastReply && chainResult.fastReplyContent) {
        sendFastReply(reply, { conversationId, model, providerName, safetyResult, content: chainResult.fastReplyContent });
        return { abort: true, messages, recalledVectorMemories, webSearchPerformed, autoGenerateDoc };
      }
      messages = chainResult.messages;
      if (!webSearchPerformed) {
        const totalRecalled =
          (chainResult.workingMemory.episodicMemories?.length || 0) +
          (chainResult.workingMemory.declarativeMemories?.length || 0) +
          (chainResult.workingMemory.proceduralMemories?.length || 0);
        if (totalRecalled > 0) {
          fastify.log.info(`[AgentChain] Injected ${totalRecalled} memory results via agent chain for user ${userId}`);
          recalledVectorMemories = {
            episodic: chainResult.workingMemory.episodicMemories || [],
            declarative: chainResult.workingMemory.declarativeMemories || [],
            procedural: chainResult.workingMemory.proceduralMemories || [],
          };
        }
      }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
    } catch (chainErr: any) {
      fastify.log.warn(`[AgentChain] Agent chain failed, continuing without: ${chainErr.message}`);
    }
  }

  ensureItalianSystemPrompt(messages);

  return { abort: false, messages, recalledVectorMemories, webSearchPerformed, autoGenerateDoc };
}
