/**
 * SafetyContentRunner — DEBT-83-G / DEBT-84-C
 *
 * Handles:
 * 1. Content safety check (AI Act GAP-10) via checkContentSafety
 * 2. Orchestration of prompt injection via PromptInjectionRunner (runPromptInjection)
 *
 * The brainstorm / RAG / free-mode injection logic is in PromptInjectionRunner.ts.
 *
 * Returns updated messages, recalledVectorMemories, webSearchPerformed, autoGenerateDoc.
 * May short-circuit (abort=true) if AgentChain fast_reply fires.
 */

import type { FastifyInstance } from 'fastify';
import type { Message } from '../../ai/providers.js';
import { ContentSafetyService } from '../../compliance/contentSafety.js';
import { SafetyResult } from '../types.js';
import { runPromptInjection, type PromptInjectionOptions } from './PromptInjectionRunner.js';

export type { PromptInjectionOptions as SafetyContentOptions };

export interface SafetyContentResult {
  /** True when AgentChain fired fast_reply (response already sent). */
  readonly abort: boolean;
  readonly messages: Message[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  readonly recalledVectorMemories: { episodic: any[]; declarative: any[]; procedural: any[] } | null;
  readonly webSearchPerformed: boolean;
  readonly autoGenerateDoc: false | 'docx' | 'pptx' | 'xlsx' | 'pdf';
}

/**
 * Run content safety check and inject appropriate system prompts based on chat mode.
 * Delegates injection logic to PromptInjectionRunner.
 * May short-circuit with abort=true if AgentChain triggers a fast_reply.
 */
export async function runSafetyAndContentInjection(
  fastify: FastifyInstance,
  opts: PromptInjectionOptions,
  messagesIn: Message[],
): Promise<SafetyContentResult> {
  return runPromptInjection(fastify, opts, messagesIn);
}

/**
 * Check content safety and return safety result.
 * Returns safetyResult (never throws — logs and falls back to safe defaults).
 */
export async function checkContentSafety(
  contentSafetyService: ContentSafetyService,
  message: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- fastify log
  log: any,
): Promise<SafetyResult> {
  let safetyResult: SafetyResult = { is_sensitive: false, topics: [], disclaimer: null, safety_flags: null };
  try {
    safetyResult = await contentSafetyService.checkMessage(message);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic/untyped interop
  } catch (safetyErr: any) {
    log.warn(`[AI-Act] Content safety check failed: ${safetyErr.message}`);
  }
  return safetyResult;
}
