import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { z } from 'zod';
import { findOne, insertOne, updateOne } from '../../database/index.js';
import { AIProviderFactory, calculateCost, Message } from '../ai/providers.js';
import { ParlantProviderFactory, checkParlantHealth } from '../../services/ParlantProvider.js';
import { saveCodeBlocks, formatSavedFilesNotification, isAutoSaveModel } from '../../services/CodeAutoSaveService.js';
import { executeTool } from '../../services/ToolService.js';
import { selectTools } from '../../services/ToolSelectionService.js';
import { MemoryService } from '../memory/service.js';
import { eventBus } from '../../services/EventBusService.js';
import { storeEpisodic } from '../../services/VectorMemoryService.js';
import { ConversationalFormService } from '../../services/ConversationalFormService.js';
import { ModelConfigService } from '../../services/ModelConfigService.js';
import { recordProviderError, recordProviderSuccess, isProviderHealthy } from '../../services/CircuitBreakerService.js';
import { ContentSafetyService } from '../compliance/contentSafety.js';
import { completionSchema, SafetyResult, ToolContext } from './types.js';
import {
  createSseWriter, writeSseHeaders, sendInitialSseEvents, sendFastReply,
  autoGenerateDocument, recordTokenComponents, recordUsageAndAudit
} from './streaming.js';
import {
  prepareToolContext, loadOrCreateConversation, injectFormContext,
  processAttachments, injectSystemPrompts, ensureItalianSystemPrompt,
  FALLBACK_MAP, isRetriableError
} from './context-builder.js';
import { getModelRouter, type RoutingDecision } from '../../services/ModelRouter.js';

export async function completionRoutes(fastify: FastifyInstance) {
  const contentSafetyService = new ContentSafetyService(fastify);
  const modelRouter = getModelRouter(fastify.db);

  fastify.post('/completions', {
    onRequest: [(fastify as any).authenticate],
    schema: {
      description: 'Send message and get AI response (streaming)',
      tags: ['chat'],
      security: [{ bearerAuth: [] }]
    }
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const user = request.user as { id: number };

    try {
      const parsedBody = completionSchema.parse(request.body);

      fastify.log.debug({ model: parsedBody.model, messageLength: parsedBody.message?.length || 0, userId: user.id, attachmentIds: parsedBody.attachmentIds || [] }, '[Chat] Request start');

      // ── Image generation check ──
      // Triggers for: model='auto' with image keywords, OR model='stable-diffusion-*' (direct diffuser model)
      const isDiffuserModel = parsedBody.model.startsWith('stable-diffusion');
      const IMAGE_PATTERN = /\b(genera|crea|creami|disegna|disegnami|fai|fammi|produci|illustra|generate|create|draw|make|paint|render)\b.*\b(immagine|immagini|foto|fotografia|disegno|illustrazione|image|picture|photo|drawing|illustration|portrait|artwork)\b/i;
      const IMAGE_KW = ['genera immagine', 'crea immagine', 'disegna', 'disegnami', 'genera foto', 'crea foto', 'crea un disegno', 'generate image', 'create image', 'draw me', 'make a picture'];
      const queryLc = parsedBody.message.toLowerCase();
      const isImageRequest = isDiffuserModel || (parsedBody.model === 'auto' && (IMAGE_PATTERN.test(parsedBody.message) || IMAGE_KW.some(kw => queryLc.includes(kw))));

      if (isImageRequest) {
        fastify.log.info(`[Router] Image generation detected for: "${parsedBody.message.substring(0, 80)}"`);
        const { generateImage } = await import('../../services/DiffuserProvider.js');
        const raw = reply.raw;
        raw.writeHead(200, {
          'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache',
          'Connection': 'keep-alive', 'X-Accel-Buffering': 'no',
        });
        const writeSse = (data: Record<string, unknown>) => {
          if (!raw.writableEnded) raw.write(`data: ${JSON.stringify(data)}\n\n`);
        };
        try {
          // Ownership check
          let imgConvId = parsedBody.conversationId;
          if (imgConvId) {
            const conv = await findOne<{ user_id: number }>(fastify.db,
              'SELECT user_id FROM conversations WHERE id = ?', [imgConvId]);
            if (!conv || conv.user_id !== user.id) {
              writeSse({ content: 'Conversazione non trovata o accesso negato.', done: false });
              writeSse({ done: true }); raw.end(); return;
            }
          }
          if (!imgConvId) {
            const title = parsedBody.message.length > 50 ? parsedBody.message.substring(0, 50) + '...' : parsedBody.message;
            imgConvId = await insertOne(fastify.db,
              'INSERT INTO conversations (user_id, title, model) VALUES (?, ?, ?)',
              [user.id, `[Image] ${title}`, 'stable-diffusion-1.5']);
          }
          await insertOne(fastify.db,
            'INSERT INTO messages (conversation_id, role, content, content_type) VALUES (?, ?, ?, ?)',
            [imgConvId, 'user', parsedBody.message, 'text']);

          writeSse({ routing: { tier: 'image', model: 'stable-diffusion-1.5', reason: 'Image generation request detected', confidence: 0.9, effort: 'medium' } });

          // Step 1: Use LLM to generate an optimized English prompt for Stable Diffusion
          writeSse({ content: 'Sto analizzando la tua richiesta e preparando il prompt per la generazione...\n\n', done: false });

          let sdPrompt = parsedBody.message; // fallback: use original prompt
          try {
            // Use a fast Ollama model to create an optimized SD prompt
            const promptGenMessages = [
              { role: 'system', content: 'You are an expert at creating Stable Diffusion image prompts. Given a user request (in any language), output ONLY a detailed English prompt optimized for Stable Diffusion 1.5. Include style keywords, lighting, composition details. Output ONLY the prompt text, nothing else.' },
              { role: 'user', content: parsedBody.message }
            ];
            const ollamaUrl = process.env.OLLAMA_BASE_URL || 'http://10.0.1.1:8086/ollama';
            const ollamaKey = process.env.OLLAMA_AUTH_KEY || '';
            const promptResponse = await fetch(`${ollamaUrl}/api/chat`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json', 'X-Ollama-Key': ollamaKey },
              body: JSON.stringify({ model: 'qwen3:30b-a3b', messages: promptGenMessages, stream: false, options: { num_predict: 200 } }),
              signal: AbortSignal.timeout(15000),
            });
            if (promptResponse.ok) {
              const promptResult = await promptResponse.json() as { message?: { content?: string } };
              const generatedPrompt = promptResult?.message?.content?.trim();
              if (generatedPrompt && generatedPrompt.length > 10) {
                sdPrompt = generatedPrompt;
                writeSse({ content: `**Prompt ottimizzato:** *${sdPrompt}*\n\nSto generando l'immagine...\n\n`, done: false });
              }
            }
          } catch {
            // LLM prompt generation failed, use original prompt
            writeSse({ content: 'Sto generando l\'immagine...\n\n', done: false });
          }

          // Step 2: Generate the image with the optimized prompt
          const result = await generateImage({ prompt: sdPrompt });

          // Step 3: Build response with image and description
          const imageMarkdown = `![Generated Image](${result.url})\n\n*Modello: ${result.model} | Risoluzione: ${result.width}x${result.height} | Seed: ${result.seed} | Tempo: ${(result.generationTimeMs / 1000).toFixed(1)}s*`;

          writeSse({ content: imageMarkdown, done: false });

          await insertOne(fastify.db,
            'INSERT INTO messages (conversation_id, role, content, content_type, ai_model, is_ai_generated) VALUES (?, ?, ?, ?, ?, 1)',
            [imgConvId, 'assistant',
              `Sto analizzando la tua richiesta e preparando il prompt per la generazione...\n\n**Prompt ottimizzato:** *${sdPrompt}*\n\nSto generando l'immagine...\n\n${imageMarkdown}`,
              'image', result.model]);

          writeSse({ done: true, conversationId: imgConvId });

          // Store in vector memory (episodic)
          storeEpisodic(fastify.db, user.id, imgConvId, parsedBody.message,
            `[Image generated] Prompt: ${sdPrompt} | Model: ${result.model} | ${result.width}x${result.height}`
          ).catch(err => fastify.log.warn(`[VectorMemory] Image episodic store failed: ${err.message}`));
        } catch (err: any) {
          fastify.log.error(`[ImageGen] Error: ${err.message}`);
          writeSse({ content: '\n\nNon sono riuscito a generare l\'immagine. Riprova piu\' tardi.', done: false });
          writeSse({ done: true });
        }
        raw.end();
        return;
      }

      // ── Model Orchestrator: auto-routing ──────────────────────────
      let routingDecision: RoutingDecision | null = null;
      let routedModel = parsedBody.model;
      if (parsedBody.model === 'auto') {
        // Get conversation message count for routing context
        let convMsgCount = 0;
        if (parsedBody.conversationId) {
          try {
            const countRow = await findOne<{ cnt: number }>(fastify.db,
              'SELECT COUNT(*) as cnt FROM messages WHERE conversation_id = ?',
              [parsedBody.conversationId]);
            convMsgCount = countRow?.cnt || 0;
          } catch { /* non-critical */ }
        }
        routingDecision = await modelRouter.route({
          query: parsedBody.message,
          conversationLength: convMsgCount,
          hasAttachments: (parsedBody.attachmentIds?.length || 0) > 0,
          attachmentCount: parsedBody.attachmentIds?.length || 0,
          hasVisionAttachments: false,
          toolsRequested: false,
          userId: user.id,
        });
        if (routingDecision.model) {
          fastify.log.info(`[Router] Auto-routed to ${routingDecision.model} (tier=${routingDecision.tier}, reason=${routingDecision.reason})`);
          routedModel = routingDecision.model;
        } else {
          // Fallback: pick first enabled chat model from DB
          const fallbackRow = await findOne<{ model_id: string }>(fastify.db,
            `SELECT m.model_id FROM ai_models m JOIN ai_providers p ON m.provider_id = p.id
             WHERE m.is_enabled = TRUE AND p.is_enabled = TRUE AND m.model_type IN ('chat','completion')
             ORDER BY m.sort_order ASC LIMIT 1`);
          if (fallbackRow) {
            routedModel = fallbackRow.model_id;
            fastify.log.warn(`[Router] No tier match, fallback to ${routedModel}`);
          } else {
            return reply.status(503).send({ error: 'No AI models available. Contact administrator.' });
          }
        }
      }
      // ── Image generation redirect ───────────────────────────────────
      if (routingDecision?.isImageGeneration) {
        fastify.log.info(`[Router] Image generation detected, redirecting to DiffuserProvider`);
        const { generateImage } = await import('../../services/DiffuserProvider.js');
        const raw = reply.raw;
        raw.writeHead(200, {
          'Content-Type': 'text/event-stream',
          'Cache-Control': 'no-cache',
          'Connection': 'keep-alive',
          'X-Accel-Buffering': 'no',
        });
        const writeSse = (data: Record<string, unknown>) => {
          if (!raw.writableEnded) raw.write(`data: ${JSON.stringify(data)}\n\n`);
        };
        try {
          // Get or create conversation (with ownership check)
          let imgConvId = parsedBody.conversationId;
          if (imgConvId) {
            const conv = await findOne<{ user_id: number }>(fastify.db,
              'SELECT user_id FROM conversations WHERE id = ?', [imgConvId]);
            if (!conv || conv.user_id !== user.id) {
              writeSse({ content: 'Conversazione non trovata o accesso negato.', done: false });
              writeSse({ done: true });
              raw.end();
              return;
            }
          }
          if (!imgConvId) {
            const title = parsedBody.message.length > 50 ? parsedBody.message.substring(0, 50) + '...' : parsedBody.message;
            imgConvId = await insertOne(fastify.db,
              'INSERT INTO conversations (user_id, title, model) VALUES (?, ?, ?)',
              [user.id, `[Image] ${title}`, 'stable-diffusion-1.5']);
          }
          // Save user message
          await insertOne(fastify.db,
            'INSERT INTO messages (conversation_id, role, content, content_type) VALUES (?, ?, ?, ?)',
            [imgConvId, 'user', parsedBody.message, 'text']);

          writeSse({ type: 'image_generating', model: 'stable-diffusion-1.5', prompt: parsedBody.message, conversationId: imgConvId });

          const result = await generateImage({ prompt: parsedBody.message });

          const imageMarkdown = `![Generated Image](${result.url})\n\n*Model: ${result.model} | ${result.width}x${result.height} | Seed: ${result.seed} | ${(result.generationTimeMs / 1000).toFixed(1)}s*`;
          await insertOne(fastify.db,
            'INSERT INTO messages (conversation_id, role, content, content_type, ai_model, is_ai_generated) VALUES (?, ?, ?, ?, ?, 1)',
            [imgConvId, 'assistant', imageMarkdown, 'image', result.model]);

          writeSse({ type: 'image_ready', url: result.url, filename: result.filename, width: result.width, height: result.height, model: result.model, seed: result.seed, generationTimeMs: result.generationTimeMs, conversationId: imgConvId });
          writeSse({ content: imageMarkdown, done: false });
          writeSse({ done: true });
        } catch (err: any) {
          fastify.log.error(`[ImageGen] Error: ${err.message}`);
          writeSse({ content: 'Non sono riuscito a generare l\'immagine. Riprova più tardi.', done: false });
          writeSse({ done: true });
        }
        raw.end();
        return;
      }

      const body = { ...parsedBody, model: routedModel };

      fastify.log.info(`[Chat] Request for model: ${body.model}`);

      // Check if this is a Parlant agent
      const isParlantAgent = body.model.startsWith('parlant:');
      let provider;
      let providerName: string;

      if (isParlantAgent) {
        const agentId = body.model.split(':')[1];
        if (!agentId || agentId.trim() === '') {
          return reply.status(400).send({ error: 'Invalid Parlant model format', message: 'Expected format: parlant:{agentId}' });
        }
        const parlantHealthy = await checkParlantHealth();
        if (!parlantHealthy) {
          fastify.log.error(`[Chat] Parlant service is not reachable`);
          return reply.status(503).send({
            error: 'Parlant service unavailable',
            message: 'The Parlant AI Agent service is not running or not reachable. Please contact your administrator.',
            hint: 'Ensure PARLANT_URL is configured and the Parlant service is running.'
          });
        }
        provider = ParlantProviderFactory.getProvider(agentId.trim(), 'Parlant Agent', `user_${user.id}`);
        providerName = 'parlant';
        fastify.log.info(`[Chat] Using Parlant agent: ${agentId}`);
      } else {
        providerName = AIProviderFactory.getProviderName(body.model);
        fastify.log.info(`[Chat] Using ${providerName} provider for model: ${body.model}`);
        provider = AIProviderFactory.getProvider(body.model);
        fastify.log.debug(`[Chat] Provider instance created: ${provider?.name || 'NULL'}`);
      }

      // Check if model supports tools
      let supportsTools = false;
      if (!isParlantAgent) {
        try {
          const modelInfo = await findOne<{ supports_functions: number }>(fastify.db, 'SELECT supports_functions FROM ai_models WHERE model_id = ?', [body.model]);
          supportsTools = modelInfo?.supports_functions === 1;
          fastify.log.info(`[Chat] Model ${body.model} tool support: ${supportsTools}`);
        } catch (err) {
          fastify.log.warn(`[Chat] Failed to check model capabilities: ${err}`);
        }
      }

      // Prepare tool context
      let toolContext: ToolContext | null = null;
      if (supportsTools) {
        try {
          toolContext = await prepareToolContext(fastify, user.id);
        } catch (err) {
          fastify.log.warn(`[Chat] Failed to load or create tool context: ${err}`);
        }
      }

      // Load or create conversation
      let result;
      try {
        result = await loadOrCreateConversation(fastify, {
          userId: user.id, conversationId: body.conversationId,
          model: body.model, providerName, systemPrompt: body.systemPrompt, messageText: body.message
        });
      } catch (err: any) {
        if (err.statusCode === 404) return reply.status(404).send({ error: err.message });
        throw err;
      }
      let { conversationId, messages } = result;

      const hookCtx = Object.freeze({ userId: user.id, conversationId });

      // Content safety check
      let safetyResult: SafetyResult = { is_sensitive: false, topics: [], disclaimer: null, safety_flags: null };
      try { safetyResult = await contentSafetyService.checkMessage(body.message); }
      catch (safetyErr: any) { fastify.log.warn(`[AI-Act] Content safety check failed: ${safetyErr.message}`); }

      // Hook: fast_reply
      const fastReplyResult = await eventBus.pipe('fast_reply', null, hookCtx);
      if (fastReplyResult.short_circuited && fastReplyResult.data) {
        sendFastReply(reply, { conversationId, model: body.model, providerName, safetyResult, content: fastReplyResult.data });
        return;
      }

      // Process user message through hooks
      let userMessage = body.message;
      const msgHook = await eventBus.pipe('before_message_read', userMessage, hookCtx);
      userMessage = msgHook.data || userMessage;
      await eventBus.emit('after_message_read', { message: userMessage, userId: user.id, conversationId }, hookCtx);

      // Conversational Form injection
      let activeFormSession: any = null;
      try {
        if (conversationId) {
          activeFormSession = await injectFormContext(fastify, user.id, conversationId, userMessage, messages);
        }
      } catch (formErr: any) {
        fastify.log.warn(`[Form] Form check failed: ${formErr.message}`);
      }

      // Handle attachments
      let nativeDocBlocks: any[] = [];
      if (body.attachmentIds && body.attachmentIds.length > 0) {
        const attachResult = await processAttachments(fastify, {
          attachmentIds: body.attachmentIds, userId: user.id,
          model: body.model, originalMessage: body.message, userMessage
        });
        nativeDocBlocks = attachResult.nativeDocBlocks;
        userMessage = attachResult.userMessage;
      }

      messages.push({ role: 'user', content: userMessage });
      await insertOne(fastify.db, 'INSERT INTO messages (conversation_id, role, content) VALUES (?, ?, ?)', [conversationId, 'user', userMessage]);

      // Inject system prompts (coding, web search, tools, doc gen, memory)
      const { webSearchPerformed, autoGenerateDoc } = await injectSystemPrompts(fastify, messages, {
        model: body.model, userMessage: body.message, userId: user.id,
        supportsTools, toolContext, attachmentIds: body.attachmentIds
      });

      // Agent Chain: memory recall + prompt templates
      let recalledVectorMemories: { episodic: any[]; declarative: any[]; procedural: any[] } | null = null;
      try {
        const { AgentChainService } = await import('../../services/AgentChainService.js');
        const agentChain = new AgentChainService(fastify, fastify.db);
        const chainResult = await agentChain.execute({
          userId: user.id, conversationId, userMessage: body.message, messages, model: body.model, hookCtx,
        });
        if (chainResult.skippedByFastReply && chainResult.fastReplyContent) {
          sendFastReply(reply, { conversationId, model: body.model, providerName, safetyResult, content: chainResult.fastReplyContent });
          return;
        }
        messages = chainResult.messages;
        const totalRecalled = (chainResult.workingMemory.episodicMemories?.length || 0) + (chainResult.workingMemory.declarativeMemories?.length || 0) + (chainResult.workingMemory.proceduralMemories?.length || 0);
        if (totalRecalled > 0) {
          fastify.log.info(`[AgentChain] Injected ${totalRecalled} memory results via agent chain for user ${user.id}`);
          recalledVectorMemories = {
            episodic: chainResult.workingMemory.episodicMemories || [],
            declarative: chainResult.workingMemory.declarativeMemories || [],
            procedural: chainResult.workingMemory.proceduralMemories || [],
          };
        }
      } catch (chainErr: any) {
        fastify.log.warn(`[AgentChain] Agent chain failed, continuing without: ${chainErr.message}`);
      }

      ensureItalianSystemPrompt(messages);

      // Set up SSE streaming
      reply.hijack();
      writeSseHeaders(reply, { conversationId, webSearchPerformed, model: body.model, providerName });
      const streamStartTime = Date.now();

      let fullResponse = '';
      let tokensInput = 0;
      let tokensOutput = 0;
      let toolDefs: ReturnType<typeof selectTools> | undefined;
      let costModel = body.model; // Tracks actual model used (may change on escalation)
      const sseWrite = createSseWriter(reply);

      sendInitialSseEvents(sseWrite, { model: body.model, providerName, safetyResult, recalledVectorMemories });

      // Send routing decision to frontend if auto-routed
      if (routingDecision) {
        sseWrite(`data: ${JSON.stringify({ routing: { tier: routingDecision.tier, model: body.model, reason: routingDecision.reason, confidence: routingDecision.confidence, effort: routingDecision.effort }, done: false })}\n\n`);
      }

      // Hook: before_llm_call
      try {
        const modelConfig = await ModelConfigService.getConfig(fastify.db, body.model);
        const llmHookData = { messages, model: body.model, temperature: modelConfig.temperature, maxTokens: modelConfig.maxOutputTokens };
        const llmHookResult = await eventBus.pipe('before_llm_call', llmHookData, hookCtx);
        if (llmHookResult.data?.messages) messages = llmHookResult.data.messages;
      } catch (hookErr: any) { fastify.log.warn(`[Hook] before_llm_call failed: ${hookErr.message}`); }

      let cacheCreationTokens = 0;
      let cacheReadTokens = 0;
      let thinkingTokens = 0;

      try {
        const modelConfig = await ModelConfigService.getConfig(fastify.db, body.model);
        toolDefs = toolContext ? selectTools(body.message) : undefined;
        const MAX_TOOL_ROUNDS = 5;
        let toolRound = 0;

        const isAnthropic = providerName === 'anthropic';
        const isOllama = providerName === 'ollama';
        const completionExtras: Record<string, any> = {};

        if (modelConfig.supportsThinking) {
          if (isAnthropic) {
            const isOpus = body.model.includes('opus');
            const maxOut = modelConfig.maxOutputTokens || 4096;
            if (isOpus) { completionExtras.thinking = { type: 'adaptive' as const }; }
            else {
              const budgetTokens = Math.min(16000, maxOut - 1024);
              if (budgetTokens >= 1024) completionExtras.thinking = { type: 'enabled' as const, budgetTokens };
            }
          } else if (isOllama) {
            // Ollama bug workaround (ollama/ollama#10976 + #11381):
            // qwen3 + tools = empty content or filtered tool calls.
            // When attachments are present, tools aren't useful (user wants content analysis),
            // so strip tools and enable thinking for best results.
            const isQwen3 = /qwen3/i.test(body.model);
            const hasAttachmentContext = (body.attachmentIds?.length || 0) > 0;
            if (isQwen3 && hasAttachmentContext && toolDefs && toolDefs.length > 0) {
              fastify.log.info(`[Chat] Ollama qwen3 + attachments: stripping tools to avoid empty response (ollama#10976/#11381)`);
              toolDefs = undefined;
              completionExtras.thinking = { type: 'enabled' as const };
            } else if (toolDefs && toolDefs.length > 0) {
              fastify.log.info(`[Chat] Ollama thinking disabled: tools present (ollama#10976 workaround)`);
            } else {
              completionExtras.thinking = { type: 'enabled' as const };
            }
          }
        }

        if (isAnthropic) {
          completionExtras.cacheControl = modelConfig.supportsCaching;
          if (nativeDocBlocks.length > 0) completionExtras.documentBlocks = nativeDocBlocks;
        }

        let continueLoop = true;
        while (continueLoop && toolRound < MAX_TOOL_ROUNDS) {
          toolRound++;
          continueLoop = false;

          const stream = provider.streamComplete({
            model: body.model, messages, maxTokens: modelConfig.maxOutputTokens,
            temperature: modelConfig.temperature, stream: true, tools: toolDefs, ...completionExtras,
          });

          let accumulatedToolCalls: any[] = [];
          let currentToolCall: any = null;
          let roundContent = '';

          for await (const chunk of stream) {
            if (chunk.thinking) sseWrite(`data: ${JSON.stringify({ thinking: chunk.thinking, done: false })}\n\n`);
            if (chunk.thinkingDone) sseWrite(`data: ${JSON.stringify({ thinkingDone: true, done: false })}\n\n`);
            if (chunk.citations?.length) sseWrite(`data: ${JSON.stringify({ citations: chunk.citations, done: false })}\n\n`);
            if (chunk.usage) {
              if (chunk.usage.cacheCreationTokens) cacheCreationTokens = chunk.usage.cacheCreationTokens;
              if (chunk.usage.cacheReadTokens) cacheReadTokens = chunk.usage.cacheReadTokens;
              if (chunk.usage.thinkingTokens) thinkingTokens = chunk.usage.thinkingTokens;
            }
            if (chunk.toolCalls && chunk.toolCalls.length > 0) {
              for (const tc of chunk.toolCalls) {
                if (tc.function && tc.function.name) {
                  if (currentToolCall) accumulatedToolCalls.push(currentToolCall);
                  currentToolCall = { id: tc.id || `tool_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`, name: tc.function.name, arguments: tc.function.arguments || '' };
                } else if (tc.function && tc.function.arguments && currentToolCall) {
                  currentToolCall.arguments += tc.function.arguments;
                }
              }
            }
            if (chunk.content) {
              fullResponse += chunk.content;
              roundContent += chunk.content;
              reply.raw.write(`data: ${JSON.stringify({ content: chunk.content, done: false })}\n\n`);
            }
          }

          if (currentToolCall) accumulatedToolCalls.push(currentToolCall);

          if (accumulatedToolCalls.length > 0 && toolContext) {
            fastify.log.info(`[Chat] Tool round ${toolRound}: executing ${accumulatedToolCalls.length} tool(s)`);
            messages.push({ role: 'assistant', content: roundContent, tool_calls: accumulatedToolCalls.map(tc => ({ id: tc.id, type: 'function', function: { name: tc.name, arguments: tc.arguments } })) } as any);

            for (const tc of accumulatedToolCalls) {
              try {
                const args = JSON.parse(tc.arguments);
                fastify.log.info(`[Chat] Executing tool: ${tc.name} (round ${toolRound})`);
                await eventBus.emit('before_tool_execute', { tool: tc.name, args, toolContext }, hookCtx);
                const result = await executeTool(tc.name, args, toolContext);
                await eventBus.emit('after_tool_execute', { tool: tc.name, args, result, toolContext }, hookCtx);
                const resultContent = result.success ? JSON.stringify(result.output) : `Error: ${result.error}`;
                messages.push({ role: 'tool', tool_call_id: tc.id, name: tc.name, content: resultContent } as any);
                if (result.success && result.output?.downloadUrl) {
                  const notification = `\n\n📄 **Documento generato**: [Scarica ${result.output.downloadFilename || result.output.path}](${result.output.downloadUrl})`;
                  reply.raw.write(`data: ${JSON.stringify({ content: notification, done: false })}\n\n`);
                  fullResponse += notification;
                } else {
                  reply.raw.write(`data: ${JSON.stringify({ toolResult: { name: tc.name, success: result.success }, done: false })}\n\n`);
                }
              } catch (e: any) {
                fastify.log.error(`[Chat] Tool execution error: ${e.message}`);
                messages.push({ role: 'tool', tool_call_id: tc.id, name: tc.name, content: `Error: ${e.message}` } as any);
              }
            }
            continueLoop = true;
          }
        }

        if (toolRound >= MAX_TOOL_ROUNDS) fastify.log.warn(`[Chat] Tool call loop hit max rounds (${MAX_TOOL_ROUNDS})`);

        // Empty response detection — known Ollama issue (think+tools=empty, or model produced no content)
        if (fullResponse.trim().length === 0 && isOllama) {
          fastify.log.warn(`[Chat] Empty response from ${body.model}, attempting escalation to balanced tier`);
          recordProviderError(body.model); // Record failure for original model
          const escalatedModel = await findOne<{ model_id: string }>(fastify.db,
            `SELECT rt.model_id FROM model_routing_tiers rt
             INNER JOIN ai_models m ON rt.model_id = m.model_id
             INNER JOIN ai_providers p ON m.provider_id = p.id
             WHERE rt.tier_name = 'balanced' AND rt.is_enabled = TRUE AND m.is_enabled = TRUE AND p.is_enabled = TRUE
               AND rt.model_id != ?
             ORDER BY rt.priority ASC LIMIT 1`, [body.model]);

          if (escalatedModel && isProviderHealthy(escalatedModel.model_id)) {
            reply.raw.write(`data: ${JSON.stringify({ content: `> Il modello ${body.model} non ha generato contenuto. Sto riprovando con ${escalatedModel.model_id}...\n\n`, done: false })}\n\n`);
            try {
              const escProvider = AIProviderFactory.getProvider(escalatedModel.model_id);
              const escConfig = await ModelConfigService.getConfig(fastify.db, escalatedModel.model_id);
              // Disable thinking for escalated Ollama call (safety — avoid same bug)
              const escStream = escProvider.streamComplete({
                model: escalatedModel.model_id, messages, maxTokens: escConfig.maxOutputTokens,
                temperature: escConfig.temperature, stream: true, tools: toolDefs,
              });
              for await (const chunk of escStream) {
                if (chunk.thinking) sseWrite(`data: ${JSON.stringify({ thinking: chunk.thinking, done: false })}\n\n`);
                if (chunk.thinkingDone) sseWrite(`data: ${JSON.stringify({ thinkingDone: true, done: false })}\n\n`);
                if (chunk.content) {
                  fullResponse += chunk.content;
                  reply.raw.write(`data: ${JSON.stringify({ content: chunk.content, done: false })}\n\n`);
                }
              }
              recordProviderSuccess(escalatedModel.model_id);
              costModel = escalatedModel.model_id;
              providerName = AIProviderFactory.getProviderName(escalatedModel.model_id);
              fastify.log.info(`[Chat] Escalation to ${escalatedModel.model_id} produced ${fullResponse.length} chars`);
            } catch (escErr: any) {
              recordProviderError(escalatedModel.model_id);
              fastify.log.error(`[Chat] Escalation stream failed: ${escErr.message}`);
            }
          }

          // If still empty after escalation, show an error message
          if (fullResponse.trim().length === 0) {
            const emptyMsg = 'Il modello non ha generato una risposta. Riprova o seleziona un modello diverso.';
            reply.raw.write(`data: ${JSON.stringify({ content: emptyMsg, done: false })}\n\n`);
            fullResponse = emptyMsg;
          }
        } else {
          recordProviderSuccess(body.model);
        }
        tokensInput = Math.ceil(messages.reduce((acc, m) => {
          const contentLen = typeof m.content === 'string' ? m.content.length : 0;
          const toolCallsLen = (m as any).tool_calls ? JSON.stringify((m as any).tool_calls).length : 0;
          return acc + (contentLen + toolCallsLen) / 4;
        }, 0));
        tokensOutput = Math.ceil(fullResponse.length / 4);

        // Post-processing: auto-generate document
        if (autoGenerateDoc) {
          try {
            const docNotification = await autoGenerateDocument(reply, fullResponse, autoGenerateDoc, body.message, fastify.log);
            fullResponse += docNotification;
          } catch (docErr: any) {
            fastify.log.error(`[Chat] Auto document generation failed: ${docErr.message}`);
            const errorNotice = `\n\nGenerazione documento fallita. Riprova o usa un formato diverso.`;
            reply.raw.write(`data: ${JSON.stringify({ content: errorNotice, done: false })}\n\n`);
            fullResponse += errorNotice;
          }
        }

        // Auto-save code blocks
        if (isAutoSaveModel(body.model) && fullResponse.length > 50) {
          try {
            const saveResult = await saveCodeBlocks(fullResponse, { projectName: `session_${conversationId}` });
            if (saveResult.savedFiles.length > 0) {
              const notification = formatSavedFilesNotification(saveResult);
              reply.raw.write(`data: ${JSON.stringify({ content: notification, done: false, autoSave: true, savedFiles: saveResult.savedFiles.map(f => ({ filename: f.filename, language: f.language, path: f.path.replace('/data/shared-projects', '\\\\192.168.1.123\\projects').replace(/\//g, '\\\\') })) })}\n\n`);
              fastify.log.info(`[Chat] Auto-saved ${saveResult.savedFiles.length} code files for model ${body.model}`);
            }
          } catch (saveError: unknown) {
            fastify.log.warn(`[Chat] Auto-save failed: ${saveError instanceof Error ? saveError.message : 'Unknown error'}`);
          }
        }

      } catch (streamError: any) {
        const errorMessage = streamError?.message || 'Unknown stream error';
        fastify.log.error(`[Chat] Stream error: ${errorMessage}`);
        recordProviderError(body.model);

        if (isRetriableError(errorMessage) && !isParlantAgent && !(request as any)._fallbackAttempted) {
          const isOllamaModel = AIProviderFactory.getProviderName(body.model) === 'ollama';
          let ollamaFallback: string | null = null;
          if (isOllamaModel && !FALLBACK_MAP[body.model]) {
            try {
              const lightRow = await findOne<any>(fastify.db, `SELECT m.model_id FROM ai_models m JOIN ai_providers p ON m.provider_id = p.id WHERE p.name = 'ollama' AND m.is_enabled = TRUE AND m.model_id != ? ORDER BY m.context_window ASC, m.sort_order ASC LIMIT 1`, [body.model]);
              ollamaFallback = lightRow?.model_id || null;
            } catch { /* no fallback */ }
          }
          const fallbackChain = FALLBACK_MAP[body.model] || (ollamaFallback ? [ollamaFallback] : []);
          const fallbackModel = fallbackChain.find(m => m !== body.model && isProviderHealthy(m)) || null;

          if (fallbackModel) {
            fastify.log.warn(`[Chat] Fallback: ${body.model} -> ${fallbackModel} (reason: ${errorMessage.substring(0, 100)})`);
            reply.raw.write(`data: ${JSON.stringify({ content: `\n\n> ⚠️ Model ${body.model} unavailable, switching to ${fallbackModel}...\n\n`, done: false })}\n\n`);
            try {
              (request as any)._fallbackAttempted = true;
              const fbProvider = AIProviderFactory.getProvider(fallbackModel);
              const fbConfig = await ModelConfigService.getConfig(fastify.db, fallbackModel);
              const fbStream = fbProvider.streamComplete({ model: fallbackModel, messages, maxTokens: fbConfig.maxOutputTokens, temperature: fbConfig.temperature, stream: true });
              for await (const chunk of fbStream) {
                if (chunk.content) { fullResponse += chunk.content; reply.raw.write(`data: ${JSON.stringify({ content: chunk.content, done: false })}\n\n`); }
              }
              recordProviderSuccess(fallbackModel);
              tokensInput = Math.ceil(messages.reduce((acc, m) => acc + m.content.length / 4, 0));
              tokensOutput = Math.ceil(fullResponse.length / 4);
              providerName = AIProviderFactory.getProviderName(fallbackModel);
            } catch (fbError: any) {
              recordProviderError(fallbackModel);
              fastify.log.error(`[Chat] Fallback also failed: ${fbError.message}`);
              reply.raw.write(`data: ${JSON.stringify({ error: 'Both primary and fallback models failed. Please try again later.', done: true })}\n\n`);
              reply.raw.end();
              return;
            }
          } else {
            let userMsg = 'An error occurred while processing your request.';
            if (errorMessage.includes('timeout')) userMsg = 'Request timed out. The AI service took too long to respond.';
            else if (errorMessage.includes('ECONNREFUSED') || errorMessage.includes('fetch failed')) userMsg = 'Could not connect to the AI service. Please try again later.';
            reply.raw.write(`data: ${JSON.stringify({ error: userMsg, done: true })}\n\n`);
            reply.raw.end();
            return;
          }
        } else {
          let userMsg = 'An error occurred while processing your request.';
          if (errorMessage.includes('Parlant')) userMsg = 'Parlant AI Agent service error: ' + errorMessage;
          else if (errorMessage.includes('timeout')) userMsg = 'Request timed out. The AI service took too long to respond.';
          else if (errorMessage.includes('ECONNREFUSED') || errorMessage.includes('fetch failed')) userMsg = 'Could not connect to the AI service. Please try again later.';
          reply.raw.write(`data: ${JSON.stringify({ error: userMsg, done: true })}\n\n`);
          reply.raw.end();
          return;
        }
      }

      // Hook: after_llm_response
      try {
        const afterLlmResult = await eventBus.pipe('after_llm_response', fullResponse, hookCtx);
        if (afterLlmResult.data && typeof afterLlmResult.data === 'string') fullResponse = afterLlmResult.data;
      } catch (hookErr: any) { fastify.log.warn(`[Hook] after_llm_response failed: ${hookErr.message}`); }

      // Conversational Form: extract JSON from LLM response
      if (activeFormSession && activeFormSession.state !== 'closed') {
        try {
          const formService = new ConversationalFormService(fastify.db);
          const jsonMatch = fullResponse.match(/```(?:json)?\s*([\s\S]*?)```/) || fullResponse.match(/(\{[\s\S]*?\})/);
          if (jsonMatch) {
            const extracted = JSON.parse(jsonMatch[1].trim());
            const formResult = await formService.updateWithExtraction(activeFormSession.id, extracted);
            fastify.log.info(`[Form] Updated session ${activeFormSession.id}: state=${formResult.state}, missing=${formResult.missing_fields.length}`);
            if (formResult.completed) {
              const completeNotice = `\n\n---\n**Form "${activeFormSession.form_name || 'form'}" completed.** Data collected successfully.`;
              reply.raw.write(`data: ${JSON.stringify({ content: completeNotice, done: false, formCompleted: true })}\n\n`);
              fullResponse += completeNotice;
              formService.executeCompleteAction(activeFormSession.form_id, formResult.collected_data, user.id)
                .then(r => { if (r.success) fastify.log.info(`[Form] on_complete_action executed: ${JSON.stringify(r.result)}`); else fastify.log.warn(`[Form] on_complete_action failed: ${r.error}`); })
                .catch(err => fastify.log.warn(`[Form] on_complete_action error: ${err.message}`));
            }
          }
        } catch (formErr: any) { fastify.log.warn(`[Form] Extraction from LLM response failed: ${formErr.message}`); }
      }

      // Hook: before_message_send
      try {
        const sendHookResult = await eventBus.pipe('before_message_send', fullResponse, hookCtx);
        if (sendHookResult.data && typeof sendHookResult.data === 'string') fullResponse = sendHookResult.data;
      } catch (hookErr: any) { fastify.log.warn(`[Hook] before_message_send failed: ${hookErr.message}`); }

      // Save assistant message (use costModel which may be the escalated model)
      const assistantMsgId = await insertOne(fastify.db,
        'INSERT INTO messages (conversation_id, role, content, tokens_input, tokens_output, is_ai_generated, ai_model, ai_provider) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
        [conversationId, 'assistant', fullResponse, tokensInput, tokensOutput, true, costModel, providerName]);

      const cost = calculateCost(costModel, tokensInput, tokensOutput);

      const usageId = await recordUsageAndAudit(fastify, {
        userId: user.id, conversationId, providerName, model: costModel,
        tokensInput, tokensOutput, cost, cacheCreationTokens, cacheReadTokens, thinkingTokens,
        assistantMsgId, userMessage, fullResponse, streamStartTime, safetyResult
      });

      try {
        await recordTokenComponents(fastify, { usageId, conversationId, userId: user.id, messages, fullResponse, toolContext, toolDefs });
      } catch (compErr: any) { fastify.log.warn(`[Chat] Component token tracking failed: ${compErr.message}`); }

      await updateOne(fastify.db, 'UPDATE conversations SET updated_at = NOW() WHERE id = ?', [conversationId]);

      // Record routing decision (async, non-blocking)
      if (routingDecision) {
        const latencyMs = Date.now() - streamStartTime;
        modelRouter.recordDecision(routingDecision, {
          query: body.message, conversationLength: messages.length,
          hasAttachments: (body.attachmentIds?.length || 0) > 0,
          attachmentCount: body.attachmentIds?.length || 0,
          hasVisionAttachments: false, toolsRequested: !!toolDefs, userId: user.id,
        }, { latencyMs, tokensInput, tokensOutput, costUsd: cost, conversationId }).catch(err =>
          fastify.log.warn(`[Router] Failed to record routing decision: ${err.message}`)
        );
      }

      // Auto-capture memory (async, non-blocking)
      try {
        const memoryService = new MemoryService(fastify.db);
        memoryService.autoCapture(user.id, conversationId, userMessage, fullResponse).catch(err => fastify.log.warn(`[Memory] Auto-capture failed: ${err.message}`));
      } catch (memErr: any) { fastify.log.warn(`[Memory] Auto-capture init failed: ${memErr.message}`); }

      // Episodic vector memory store
      try {
        const memData = { userMessage: body.message, assistantResponse: fullResponse };
        const memHook = await eventBus.pipe('before_memory_store', memData, hookCtx);
        const finalMem = memHook.data || memData;
        storeEpisodic(fastify.db, user.id, conversationId, finalMem.userMessage, finalMem.assistantResponse).catch(err => fastify.log.warn(`[VectorMemory] Episodic store failed: ${err.message}`));
      } catch (memErr: any) { fastify.log.warn(`[VectorMemory] Store hook failed: ${memErr.message}`); }

      eventBus.emit('after_message_send', { userMessage: body.message, assistantResponse: fullResponse, model: body.model, provider: providerName, tokensInput, tokensOutput, cost }, hookCtx).catch(() => {});

      reply.raw.write(`data: ${JSON.stringify({ content: '', done: true, conversationId })}\n\n`);
      reply.raw.end();

    } catch (err) {
      if (err instanceof z.ZodError) return reply.status(400).send({ error: 'Validation failed', details: err.errors });
      throw err;
    }
  });
}
