import path from 'path';
import { randomUUID } from 'crypto';
import { FastifyInstance } from 'fastify';
import { insertOne } from '../../database/index.js';
import { Message } from '../ai/providers.js';
import { SafetyResult } from './types.js';

/**
 * Safe SSE write — silently skips if client disconnected.
 */
export function createSseWriter(reply: any) {
  return (data: string) => {
    if (!reply.raw.destroyed) reply.raw.write(data);
  };
}

/**
 * Write standard SSE headers for a chat streaming response.
 */
export function writeSseHeaders(
  reply: any,
  opts: {
    conversationId: number;
    webSearchPerformed: boolean;
    model: string;
    providerName: string;
  }
): void {
  reply.raw.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
    'X-Conversation-Id': opts.conversationId.toString(),
    'X-Web-Search': opts.webSearchPerformed ? 'true' : 'false',
    'X-AI-Generated': 'true',
    'X-AI-Model': opts.model,
    'X-AI-Provider': opts.providerName,
    'X-AI-Disclosure': 'This content is generated by artificial intelligence'
  });
}

/**
 * Send the initial SSE disclosure, content-safety warning, and vector memory events.
 */
export function sendInitialSseEvents(
  sseWrite: (data: string) => void,
  opts: {
    model: string;
    providerName: string;
    safetyResult: SafetyResult;
    recalledVectorMemories: { episodic: any[]; declarative: any[]; procedural: any[] } | null;
  }
): void {
  // AI Act Art. 50: Send disclosure event before content
  sseWrite(`data: ${JSON.stringify({ type: 'ai_disclosure', model: opts.model, provider: opts.providerName })}\n\n`);

  // AI Act GAP-10: Send content safety warning BEFORE the LLM stream
  if (opts.safetyResult.is_sensitive && opts.safetyResult.disclaimer) {
    sseWrite(`data: ${JSON.stringify({ type: 'content_safety_warning', disclaimer: opts.safetyResult.disclaimer, topics: opts.safetyResult.topics })}\n\n`);
  }

  // Emit vector memory recall results to frontend
  if (opts.recalledVectorMemories) {
    sseWrite(`data: ${JSON.stringify({ type: 'vector_memories', memories: opts.recalledVectorMemories })}\n\n`);
  }
}

/**
 * Send fast-reply short-circuit response via SSE.
 */
export function sendFastReply(
  reply: any,
  opts: {
    conversationId: number;
    model: string;
    providerName: string;
    safetyResult: SafetyResult;
    content: string;
    extra?: Record<string, unknown>;
  }
): void {
  reply.hijack();
  reply.raw.writeHead(200, {
    'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', 'Connection': 'keep-alive',
    'X-Conversation-Id': opts.conversationId.toString(),
    'X-AI-Generated': 'true', 'X-AI-Model': opts.model, 'X-AI-Provider': opts.providerName,
    'X-AI-Disclosure': 'This content is generated by artificial intelligence'
  });
  reply.raw.write(`data: ${JSON.stringify({ type: 'ai_disclosure', model: opts.model, provider: opts.providerName })}\n\n`);
  if (opts.safetyResult.is_sensitive && opts.safetyResult.disclaimer) {
    reply.raw.write(`data: ${JSON.stringify({ type: 'content_safety_warning', disclaimer: opts.safetyResult.disclaimer, topics: opts.safetyResult.topics })}\n\n`);
  }
  if (opts.extra) {
    for (const [type, payload] of Object.entries(opts.extra)) {
      reply.raw.write(`data: ${JSON.stringify({ type, ...(payload as Record<string, unknown>) })}\n\n`);
    }
  }
  reply.raw.write(`data: ${JSON.stringify({ content: opts.content })}\n\n`);
  reply.raw.write('data: [DONE]\n\n');
  reply.raw.end();
}

/**
 * Auto-generate a document (DOCX, PPTX, XLSX, PDF) from the AI response content.
 * Returns the notification string appended to the response, or empty string if not applicable.
 */
export async function autoGenerateDocument(
  reply: any,
  fullResponse: string,
  autoGenerateDoc: 'docx' | 'pptx' | 'xlsx' | 'pdf',
  messageText: string,
  log: any
): Promise<string> {
  const toolAlreadyGeneratedDoc = fullResponse.includes('/api/tools/download/');
  if (toolAlreadyGeneratedDoc || fullResponse.trim().length <= 50) {
    return '';
  }

  let docContent = fullResponse;

  // Clean up: remove common AI preambles
  const preamblePatterns = [
    /^(?:ecco|qui|di seguito)[^:.\n]*[:.]?\s*\n/i,
    /^(?:here is|below is|the following is)[^:.\n]*[:.]?\s*\n/i,
    /^(?:certamente|certo|ok|sì)[^:.\n]*[:.]?\s*\n/i,
  ];
  for (const pattern of preamblePatterns) {
    docContent = docContent.replace(pattern, '');
  }

  // Remove trailing AI commentary
  const trailingPatterns = [
    /\n\n(?:se hai|fammi sapere|spero|non esitare|let me know|feel free|hope this)[^\n]*$/i,
    /\n\n---\n\n?(?:nota|note|n\.b\.)[^\n]*$/i,
  ];
  for (const pattern of trailingPatterns) {
    docContent = docContent.replace(pattern, '');
  }

  // Strip markdown bold/italic for cleaner documents
  const cleanContent = docContent.trim()
    .replace(/```[\s\S]*?```/g, (match) => match.replace(/```\w*\n?/g, '').replace(/```/g, ''))
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1');

  if (cleanContent.length <= 30) {
    return '';
  }

  const titleMatch = messageText.match(/(?:titolo|title)[:\s]+"?([^"\n]+)"?/i);
  const docTitle = titleMatch ? titleMatch[1].trim().substring(0, 100) : 'Documento_Generato';

  const { generateDocxBuffer, generatePptxBuffer, generateExcelBuffer, convertOfficeToPdf } = await import('../../services/DocumentProcessorService.js');
  const fsImport = await import('fs/promises');
  const pathImport = await import('path');
  const generatedDir = pathImport.default.join(process.env.STORAGE_ROOT || process.cwd(), 'generated');
  await fsImport.mkdir(generatedDir, { recursive: true });

  let buffer: Buffer;
  let ext: string;
  let icon: string;

  switch (autoGenerateDoc) {
    case 'pptx': {
      // Smart parsing: split by markdown headings, preserving heading text as slide title
      const slideChunks: { title: string; content: string }[] = [];
      const headingRegex = /^(#{1,3})\s+(.+)$/gm;
      let match: RegExpExecArray | null;
      const headings: { index: number; title: string }[] = [];

      while ((match = headingRegex.exec(cleanContent)) !== null) {
        headings.push({ index: match.index, title: match[2].trim() });
      }

      if (headings.length > 0) {
        const preContent = cleanContent.substring(0, headings[0].index).trim();
        if (preContent.length > 30) {
          const preLines = preContent.split('\n').filter(l => l.trim());
          slideChunks.push({
            title: preLines[0]?.substring(0, 100) || 'Introduzione',
            content: preLines.slice(1).join('\n').trim() || preContent
          });
        }
        for (let hi = 0; hi < headings.length; hi++) {
          const start = headings[hi].index;
          const end = hi + 1 < headings.length ? headings[hi + 1].index : cleanContent.length;
          const sectionText = cleanContent.substring(start, end).trim();
          const bodyText = sectionText.replace(/^#{1,3}\s+.+\n?/, '').trim();
          slideChunks.push({
            title: headings[hi].title.substring(0, 100),
            content: bodyText
          });
        }
      } else {
        const sections = cleanContent.split(/\n\n\n+/).filter(s => s.trim());
        for (let si = 0; si < sections.length; si++) {
          const lines = sections[si].trim().split('\n');
          slideChunks.push({
            title: lines[0]?.substring(0, 100) || `Slide ${si + 1}`,
            content: lines.slice(1).join('\n').trim() || lines[0] || ''
          });
        }
      }

      buffer = await generatePptxBuffer(
        slideChunks.length > 0 ? slideChunks : [{ title: docTitle, content: cleanContent }],
        docTitle
      );
      ext = 'pptx';
      icon = '📊';
      break;
    }
    case 'xlsx': {
      const lines = cleanContent.split('\n').filter(l => l.trim());
      const data = lines.map((line, i) => ({ riga: i + 1, contenuto: line.trim() }));
      buffer = await generateExcelBuffer(data, docTitle);
      ext = 'xlsx';
      icon = '📈';
      break;
    }
    case 'pdf': {
      const docxBuf = await generateDocxBuffer(cleanContent, docTitle);
      const tmpName = `_tmp_${Date.now()}_${randomUUID().slice(0, 8)}.docx`;
      const tmpPath = pathImport.default.join(generatedDir, tmpName);
      await fsImport.writeFile(tmpPath, docxBuf);
      let pdfPath: string | undefined;
      try {
        pdfPath = await convertOfficeToPdf(docxBuf, generatedDir, tmpName);
        buffer = await fsImport.readFile(pdfPath);
      } finally {
        await fsImport.unlink(tmpPath).catch(() => {});
        if (pdfPath) await fsImport.unlink(pdfPath).catch(() => {});
      }
      ext = 'pdf';
      icon = '📕';
      break;
    }
    default: { // docx
      buffer = await generateDocxBuffer(cleanContent, docTitle);
      ext = 'docx';
      icon = '📄';
      break;
    }
  }

  const filename = `${docTitle.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.${ext}`;
  const filePath = pathImport.default.join(generatedDir, filename);
  await fsImport.writeFile(filePath, buffer);

  const downloadUrl = `/api/tools/download/${filename}`;
  const downloadNotification = `\n\n${icon} **Documento generato con successo!** [Scarica ${docTitle}.${ext}](${downloadUrl})`;

  reply.raw.write(`data: ${JSON.stringify({ content: downloadNotification, done: false })}\n\n`);

  log.info(`[Chat] Auto-generated ${ext.toUpperCase()} from AI response -> ${filename} (${cleanContent.length} chars)`);

  return downloadNotification;
}

/**
 * Detect if the user wants a PURE format conversion (no AI processing needed).
 * Returns true for messages like "converti il pdf in docx", "trasforma in word", etc.
 * Returns false if the user wants elaboration, translation, summary, or content changes.
 */
export function isDirectConversionRequest(message: string, hasAttachments: boolean): boolean {
  if (!hasAttachments) return false;
  const msgLower = message.toLowerCase();

  // Explicit conversion verbs: "converti il pdf in docx", "trasforma in word"
  const hasConversionVerb = /\b(converti|trasforma|convertire|convertilo|convert|transform)\w*\b/i.test(msgLower);

  // "Create format FROM attachment" patterns:
  // "creami un file docx del pdf", "genera un word dal pdf", "fai un docx dell'allegato"
  const hasCreateFromAttachment =
    /\b(crea|genera|fa[im]|dammi|metti)\w*\b/i.test(msgLower) &&
    /\b(docx|word|pdf)\b/i.test(msgLower) &&
    /\b(del|dal|dell['a]?|dall['a]?|di\s+questo|from|of the)\b/i.test(msgLower);

  if (!hasConversionVerb && !hasCreateFromAttachment) return false;

  // Must NOT have elaboration verbs (translate, summarize, modify, etc.)
  const hasElaborationVerb = /\b(traduci|riassumi|modifica|cambia|migliora|riscrivi|analizza|estrai|translate|summarize|modify|rewrite|analyze|extract)\w*\b/i.test(msgLower);
  if (hasElaborationVerb) return false;

  // Short message (under ~150 chars) = likely pure conversion request
  return msgLower.length < 150;
}

/**
 * Directly convert an attachment to the target format WITHOUT LLM inference.
 * Returns the SSE response content string (with download link), or null if conversion fails.
 */
export async function directConvertAttachment(
  _reply: any,
  db: any,
  userId: number,
  attachmentIds: number[],
  targetFormat: 'docx' | 'pdf',
  _messageText: string,
  log: any,
): Promise<string | null> {
  try {
    const { findOne } = await import('../../database/index.js');
    const attachment = await findOne<any>(
      db,
      'SELECT processed_content, original_name, file_path, mime_type FROM chat_attachments WHERE id = ? AND user_id = ?',
      [attachmentIds[0], userId]
    );

    if (!attachment?.processed_content || attachment.processed_content.length < 30) {
      return null; // Not enough content, fall through to LLM
    }

    const baseName = attachment.original_name?.replace(/\.[^.]+$/, '') || 'Documento';
    const docTitle = baseName.substring(0, 100);

    const { generateDocxBuffer, convertOfficeToPdf, convertPdfToDocx } = await import('../../services/DocumentProcessorService.js');
    const fs = await import('fs/promises');
    const pathMod = await import('path');
    const generatedDir = pathMod.default.join(process.env.STORAGE_ROOT || process.cwd(), 'generated');
    await fs.mkdir(generatedDir, { recursive: true });

    let buffer: Buffer;
    let ext: string;
    let icon: string;

    const isPdf = attachment.mime_type === 'application/pdf' ||
      attachment.original_name?.toLowerCase().endsWith('.pdf');

    if (targetFormat === 'pdf') {
      const content = attachment.processed_content;
      const docxBuf = await generateDocxBuffer(content, docTitle);
      const tmpName = `_tmp_${Date.now()}_${randomUUID().slice(0, 8)}.docx`;
      const tmpPath = pathMod.default.join(generatedDir, tmpName);
      await fs.writeFile(tmpPath, docxBuf);
      let pdfPath: string | undefined;
      try {
        pdfPath = await convertOfficeToPdf(docxBuf, generatedDir, tmpName);
        buffer = await fs.readFile(pdfPath);
      } finally {
        await fs.unlink(tmpPath).catch(() => {});
        if (pdfPath) await fs.unlink(pdfPath).catch(() => {});
      }
      ext = 'pdf';
      icon = '📕';
    } else if (isPdf) {
      // PDF→DOCX: smart conversion with structure preservation
      const { convertPdfToDocxSmart, convertPdfToDocxOcr } = await import('../../services/document-processing/PDFConversionService.js');

      if (!attachment.file_path) return null;
      const pdfBuffer = await fs.readFile(attachment.file_path);

      try {
        buffer = await convertPdfToDocxSmart(pdfBuffer, docTitle);
        log.info(`[Chat] PDF→DOCX smart conversion: ${attachment.original_name}`);
      } catch (smartErr) {
        log.warn(`[Chat] Smart conversion failed, falling back to OCR: ${smartErr}`);
        buffer = await convertPdfToDocxOcr(pdfBuffer, docTitle);
        log.info(`[Chat] PDF→DOCX OCR fallback: ${attachment.original_name}`);
      }
      ext = 'docx';
      icon = '📄';
    } else {
      // Non-PDF source: generate DOCX from extracted text
      const content = attachment.processed_content;
      buffer = await generateDocxBuffer(content, docTitle);
      ext = 'docx';
      icon = '📄';
    }

    const filename = `${docTitle.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.${ext}`;
    const filePath = pathMod.default.join(generatedDir, filename);
    await fs.writeFile(filePath, buffer);

    const downloadUrl = `/api/tools/download/${filename}`;
    log.info(`[Chat] Direct conversion: ${attachment.original_name} -> ${ext.toUpperCase()} (no LLM)`);

    return `Ho convertito il file "${attachment.original_name}" in formato ${ext.toUpperCase()}.\n\n${icon} **Documento convertito con successo!** [Scarica ${docTitle}.${ext}](${downloadUrl})`;
  } catch (err: any) {
    log.error(`[Chat] Direct conversion failed: ${err.message}`);
    return null; // Fall through to LLM
  }
}

/**
 * Detect which document format (if any) the user is requesting based on their message.
 */
export function detectDocumentFormat(
  message: string,
  attachmentIds?: number[]
): false | 'docx' | 'pptx' | 'xlsx' | 'pdf' {
  const msgLower = message.toLowerCase();
  const hasAttachments = attachmentIds && attachmentIds.length > 0;
  // Italian verbs: match all conjugations (creami, creare, generami, etc.) by dropping trailing \b
  // Also includes "voglio" (lo voglio in pdf), "dammi" (dammi il pdf), "metti" (mettilo in pdf)
  const hasCreationVerb = /\b(crea|genera|salva|esporta|converti|trasforma|fa[im]|scrivi|produci|voglio|dammi|metti)\w*\b/i.test(msgLower)
    || /\b(create|generate|save|export|convert|make|write)\b/i.test(msgLower);

  const mentionsPptx = /\b(powerpoint|pptx|\.pptx|presentazione|slides?|diapositiv[ae])\b/i.test(msgLower);
  const mentionsXlsx = /\b(excel|xlsx|\.xlsx|foglio.*calcolo|spreadsheet|tabella)\b/i.test(msgLower);
  const mentionsPdf = /\b(pdf|\.pdf)\b/i.test(msgLower) && hasCreationVerb;
  const mentionsWord = /\b(word|docx|\.docx)\b/i.test(msgLower);

  const pptxKeywords = ['crea powerpoint', 'crea presentazione', 'genera presentazione', 'genera powerpoint',
    'crea slide', 'genera slide', 'fai una presentazione', 'crea pptx', 'create a powerpoint',
    'create a presentation', 'generate a presentation', 'make a presentation', 'creami una presentazione',
    'creami un powerpoint', 'fai un powerpoint'];
  const xlsxKeywords = ['crea excel', 'genera excel', 'crea foglio', 'crea tabella', 'genera tabella',
    'crea xlsx', 'create a spreadsheet', 'create an excel', 'generate a spreadsheet',
    'creami un excel', 'fai un excel', 'esporta in excel'];
  const docGenKeywords = ['crea word', 'genera docx', 'crea documento', 'salva come word',
    'traduci e crea', 'traduci e salva', 'crea un file', 'create a word', 'create a document',
    'generate a docx', 'save as word', 'make a word', 'creami un file', 'crea file word',
    'creami un documento', 'crea un documento', 'converti in word', 'esporta in word',
    'genera un documento', 'genera documento', 'crea il word', 'crea il documento',
    'salva in word', 'salva come documento', 'converti in docx', 'trasforma in word',
    'convertilo in word', 'fai un word', 'fai un documento', 'crea il file',
    'file docx', 'file word', 'in un file docx', 'in un file word',
    'convert to word', 'convert to docx', 'convert into word', 'convert into docx',
    'convertire in docx', 'convertire in word', 'convertilo in docx'];

  const hasPptxKeyword = pptxKeywords.some(kw => msgLower.includes(kw));
  const hasXlsxKeyword = xlsxKeywords.some(kw => msgLower.includes(kw));
  const hasDocxKeyword = docGenKeywords.some(kw => msgLower.includes(kw));

  if (hasPptxKeyword || (mentionsPptx && hasCreationVerb) || (hasAttachments && mentionsPptx)) {
    return 'pptx';
  } else if (hasXlsxKeyword || (mentionsXlsx && hasCreationVerb) || (hasAttachments && mentionsXlsx)) {
    return 'xlsx';
  } else if (mentionsPdf && !mentionsWord) {
    return 'pdf';
  } else if (hasDocxKeyword || (mentionsWord && hasCreationVerb) || (hasAttachments && mentionsWord) || (hasAttachments && /\b(docx|\.docx)\b/i.test(msgLower))) {
    return 'docx';
  }

  return false;
}

/**
 * Record per-component token breakdown (GAP 8).
 */
export async function recordTokenComponents(
  fastify: FastifyInstance,
  opts: {
    usageId: number | null;
    conversationId: number;
    userId: number;
    messages: Message[];
    fullResponse: string;
    toolContext: any;
    toolDefs: any;
  }
): Promise<void> {
  const estTokens = (text: string) => Math.ceil((text || '').length / 4);
  const components: { component: string; tokens: number }[] = [];

  const memoryMarkers = ['## Relevant past conversations', '## Relevant knowledge', '## Available tools/procedures', '## Agent suggestion'];

  for (const msg of opts.messages) {
    if (msg.role === 'system') {
      const content = msg.content || '';
      let memoryTokens = 0;
      for (const marker of memoryMarkers) {
        const idx = content.indexOf(marker);
        if (idx >= 0) {
          const nextIdx = memoryMarkers
            .map(m => content.indexOf(m, idx + marker.length))
            .filter(i => i > idx)
            .sort((a, b) => a - b)[0] || content.length;
          memoryTokens += estTokens(content.substring(idx, nextIdx));
        }
      }
      const basePromptTokens = Math.max(0, estTokens(content) - memoryTokens);
      components.push({ component: 'system_prompt', tokens: basePromptTokens });
      if (memoryTokens > 0) {
        components.push({ component: 'memory_context', tokens: memoryTokens });
      }
    } else if (msg.role === 'user') {
      components.push({ component: 'user_message', tokens: estTokens(msg.content) });
    } else if (msg.role === 'tool') {
      components.push({ component: 'tool_results', tokens: estTokens(msg.content) });
    }
  }

  if (opts.toolContext && opts.toolDefs) {
    components.push({ component: 'tool_definitions', tokens: estTokens(JSON.stringify(opts.toolDefs)) });
  }

  components.push({ component: 'assistant_response', tokens: estTokens(opts.fullResponse) });

  for (const c of components) {
    await fastify.db.execute(
      'INSERT INTO token_usage_components (usage_id, conversation_id, user_id, component, tokens_estimate) VALUES (?, ?, ?, ?, ?)',
      [opts.usageId, opts.conversationId, opts.userId, c.component, c.tokens]
    );
  }
}

/**
 * Record usage stats in token_usage and monthly_usage tables, AI Act labels and decision log.
 */
export async function recordUsageAndAudit(
  fastify: FastifyInstance,
  opts: {
    userId: number;
    conversationId: number;
    providerName: string;
    model: string;
    tokensInput: number;
    tokensOutput: number;
    cost: number;
    cacheCreationTokens: number;
    cacheReadTokens: number;
    thinkingTokens: number;
    assistantMsgId: number;
    userMessage: string;
    fullResponse: string;
    streamStartTime: number;
    safetyResult: { safety_flags: Record<string, boolean> | null };
  }
): Promise<number | null> {
  // Record token usage (v4.0: includes cache + thinking metrics)
  const [usageResult] = await fastify.db.execute(
    `INSERT INTO token_usage (user_id, conversation_id, provider, model, tokens_input, tokens_output, cost_usd,
     cache_creation_tokens, cache_read_tokens, thinking_tokens) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [opts.userId, opts.conversationId, opts.providerName, opts.model, opts.tokensInput, opts.tokensOutput, opts.cost,
     opts.cacheCreationTokens, opts.cacheReadTokens, opts.thinkingTokens]
  ) as any;
  const usageId = usageResult?.insertId || null;

  // Update monthly usage
  const yearMonth = new Date().toISOString().slice(0, 7);
  await fastify.db.execute(
    `INSERT INTO monthly_usage (user_id, \`year_month\`, provider, total_tokens_input, total_tokens_output, total_cost_usd, request_count)
     VALUES (?, ?, ?, ?, ?, ?, 1)
     ON DUPLICATE KEY UPDATE
     total_tokens_input = total_tokens_input + VALUES(total_tokens_input),
     total_tokens_output = total_tokens_output + VALUES(total_tokens_output),
     total_cost_usd = total_cost_usd + VALUES(total_cost_usd),
     request_count = request_count + 1`,
    [opts.userId, yearMonth, opts.providerName, opts.tokensInput, opts.tokensOutput, opts.cost]
  );

  // AI Act GAP-2: Insert ai_content_labels record — non-blocking
  try {
    await insertOne(fastify.db,
      `INSERT INTO ai_content_labels (message_id, content_type, ai_model, ai_provider) VALUES (?, ?, ?, ?)`,
      [opts.assistantMsgId, 'chat_response', opts.model, opts.providerName]
    );
  } catch (labelErr: any) {
    fastify.log.warn(`[AI-Act] Content label insert failed: ${labelErr.message}`);
  }

  // AI Act GAP-5: Log AI decision — non-blocking
  try {
    const { createHash } = await import('crypto');
    const promptHash = createHash('sha256').update(opts.userMessage).digest('hex').slice(0, 64);
    const responseHash = createHash('sha256').update(opts.fullResponse).digest('hex').slice(0, 64);
    const latencyMs = typeof opts.streamStartTime === 'number' ? Date.now() - opts.streamStartTime : 0;
    const safetyFlagsJson = opts.safetyResult.safety_flags ? JSON.stringify(opts.safetyResult.safety_flags) : null;
    await insertOne(fastify.db,
      `INSERT INTO ai_decision_log (user_id, conversation_id, message_id, ai_model, ai_provider, prompt_hash, response_hash, tokens_input, tokens_output, latency_ms, safety_flags, disclosure_shown)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [opts.userId, opts.conversationId, opts.assistantMsgId, opts.model, opts.providerName, promptHash, responseHash, opts.tokensInput, opts.tokensOutput, latencyMs, safetyFlagsJson, true]
    );
  } catch (decisionLogErr: any) {
    fastify.log.warn(`[AI-Act] Decision log failed: ${decisionLogErr.message}`);
  }

  return usageId;
}
